/* This file is automatically generated by Lemon from input grammar
** source file "parser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <assert.h>

#include "parse.h"
#include "util/arr.h"
#include "rmutil/vector.h"
#include "query_node.h"
#include "vector_index.h"
#include "query_param.h"
#include "query_internal.h"
#include "util/strconv.h"

// strndup + lowercase in one pass!
char *strdupcase(const char *s, size_t len) {
  char *ret = rm_strndup(s, len);
  char *dst = ret;
  char *src = dst;
  while (*src) {
      // unescape 
      if (*src == '\\' && (ispunct(*(src+1)) || isspace(*(src+1)))) {
          ++src;
          continue;
      }
      *dst = tolower(*src);
      ++dst;
      ++src;

  }
  *dst = '\0';
  
  return ret;
}

// unescape a string (non null terminated) and return the new length (may be shorter than the original. This manipulates the string itself 
size_t unescapen(char *s, size_t sz) {
  
  char *dst = s;
  char *src = dst;
  char *end = s + sz;
  while (src < end) {
      // unescape 
      if (*src == '\\' && src + 1 < end &&
         (ispunct(*(src+1)) || isspace(*(src+1)))) {
          ++src;
          continue;
      }
      *dst++ = *src++;
  }
 
  return (size_t)(dst - s);
}

#define NODENN_BOTH_VALID 0
#define NODENN_BOTH_INVALID -1
#define NODENN_ONE_NULL 1 
// Returns:
// 0 if a && b
// -1 if !a && !b
// 1 if a ^ b (i.e. !(a&&b||!a||!b)). The result is stored in `out` 
static int one_not_null(void *a, void *b, void *out) {
    if (a && b) {
        return NODENN_BOTH_VALID;
    } else if (a == NULL && b == NULL) {
        return NODENN_BOTH_INVALID;
    } if (a) {
        *(void **)out = a;
        return NODENN_ONE_NULL;
    } else {
        *(void **)out = b;
        return NODENN_ONE_NULL;
    }
}

void setup_trace(QueryParseCtx *ctx) {
#ifdef PARSER_DEBUG
  void RSQueryParser_Trace(FILE*, char*);
  ctx->trace_log = fopen("/tmp/lemon_query.log", "w");
  RSQueryParser_Trace(ctx->trace_log, "tr: ");
#endif
}

void reportSyntaxError(QueryError *status, QueryToken* tok, const char *msg) {
  if (tok->type == QT_TERM || tok->type == QT_TERM_CASE) {
    QueryError_SetErrorFmt(status, QUERY_ESYNTAX,
      "%s at offset %d near %.*s", msg, tok->pos, tok->len, tok->s);
  } else if (tok->type == QT_NUMERIC) {
    QueryError_SetErrorFmt(status, QUERY_ESYNTAX,
      "%s at offset %d near %f", msg, tok->pos, tok->numval);
  } else {
    QueryError_SetErrorFmt(status, QUERY_ESYNTAX, "%s at offset %d", msg, tok->pos);
  }
}

/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef LOWEST
#define LOWEST                          1
#define TILDE                           2
#define TAGLIST                         3
#define QUOTE                           4
#define COLON                           5
#define MINUS                           6
#define NUMBER                          7
#define STOPWORD                        8
#define TERMLIST                        9
#define TERM                           10
#define PREFIX                         11
#define SUFFIX                         12
#define CONTAINS                       13
#define PERCENT                        14
#define ATTRIBUTE                      15
#define LP                             16
#define RP                             17
#define MODIFIER                       18
#define AND                            19
#define OR                             20
#define ORX                            21
#define ARROW                          22
#define STAR                           23
#define SEMICOLON                      24
#define LB                             25
#define RB                             26
#define LSQB                           27
#define RSQB                           28
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    RSQueryParser_TOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is RSQueryParser_TOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    RSQueryParser_ARG_SDECL     A static variable declaration for the %extra_argument
**    RSQueryParser_ARG_PDECL     A parameter declaration for the %extra_argument
**    RSQueryParser_ARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    RSQueryParser_ARG_STORE     Code to store %extra_argument into yypParser
**    RSQueryParser_ARG_FETCH     Code to extract %extra_argument from yypParser
**    RSQueryParser_CTX_*         As RSQueryParser_ARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 49
#define YYACTIONTYPE unsigned short int
#define RSQueryParser_TOKENTYPE QueryToken
typedef union {
  int yyinit;
  RSQueryParser_TOKENTYPE yy0;
  QueryAttribute yy13;
  QueryAttribute * yy14;
  QueryNode * yy21;
  QueryParam * yy22;
  Vector* yy64;
  RangeNumber yy83;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define RSQueryParser_ARG_SDECL  QueryParseCtx *ctx ;
#define RSQueryParser_ARG_PDECL , QueryParseCtx *ctx 
#define RSQueryParser_ARG_PARAM ,ctx 
#define RSQueryParser_ARG_FETCH  QueryParseCtx *ctx =yypParser->ctx ;
#define RSQueryParser_ARG_STORE yypParser->ctx =ctx ;
#define RSQueryParser_CTX_SDECL
#define RSQueryParser_CTX_PDECL
#define RSQueryParser_CTX_PARAM
#define RSQueryParser_CTX_FETCH
#define RSQueryParser_CTX_STORE
#define YYNSTATE             67
#define YYNRULE              70
#define YYNRULE_WITH_ACTION  70
#define YYNTOKEN             29
#define YY_MAX_SHIFT         66
#define YY_MIN_SHIFTREDUCE   118
#define YY_MAX_SHIFTREDUCE   187
#define YY_ERROR_ACTION      188
#define YY_ACCEPT_ACTION     189
#define YY_NO_ACTION         190
#define YY_MIN_REDUCE        191
#define YY_MAX_REDUCE        260
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (357)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   202,   44,    5,  260,   19,   59,    6,  182,  142,   48,
 /*    10 */   181,  148,  149,  150,   26,  183,    7,  127,  157,  191,
 /*    20 */     9,    5,   66,   19,   66,    6,  182,  142,   65,  181,
 /*    30 */   148,  149,  150,   26,  183,    7,  192,  157,    5,    9,
 /*    40 */    19,   66,    6,  182,  142,   60,  181,  148,  149,  150,
 /*    50 */    26,  183,    7,  217,  157,  182,  145,   61,  181,   47,
 /*    60 */    62,   57,    5,  183,   19,   63,    6,  182,  142,  250,
 /*    70 */   181,  148,  149,  150,   26,  183,    7,  181,  157,   32,
 /*    80 */   176,  236,  183,  186,   29,   17,  251,   23,  184,   28,
 /*    90 */    19,  216,    6,  182,  142,   34,  181,  148,  149,  150,
 /*   100 */    26,  183,    7,  260,  157,    9,    9,   66,   66,   20,
 /*   110 */   182,  162,  201,  181,  148,  149,  150,   13,  183,  260,
 /*   120 */   211,  212,  213,   41,  195,   21,   43,  245,  247,   45,
 /*   130 */   231,  243,  180,   46,   36,  179,    5,  260,   19,  232,
 /*   140 */     6,  182,  142,   22,  181,  148,  149,  150,   26,  183,
 /*   150 */     7,  203,  157,  182,  142,  193,  181,  148,  149,  150,
 /*   160 */    26,  183,    7,   18,  157,  173,    9,   27,   66,  169,
 /*   170 */     3,   32,  176,  211,  212,  213,   41,  195,   37,   64,
 /*   180 */   185,   33,   45,  154,  155,  189,   46,   36,   14,   50,
 /*   190 */   156,  211,  212,  213,   41,  195,   42,    8,  133,  240,
 /*   200 */    45,   52,   30,    4,   46,   36,  211,  212,  213,   41,
 /*   210 */   195,   53,   40,   35,    1,   45,   32,  176,   11,   46,
 /*   220 */    36,  211,  212,  213,   41,  195,   33,  153,   55,   39,
 /*   230 */    45,   56,  152,    2,   46,   36,  211,  212,  213,   41,
 /*   240 */   195,   58,  151,  253,  252,   45,  136,  135,   12,   46,
 /*   250 */    36,  211,  212,  213,   41,  195,   38,   24,  190,  190,
 /*   260 */    45,  190,  190,   15,   46,   36,  211,  212,  213,   41,
 /*   270 */   195,  190,  190,  190,  190,   45,  190,  190,   16,   46,
 /*   280 */    36,  211,  212,  213,   41,  195,  190,   32,  176,  190,
 /*   290 */    45,  186,  190,  190,   46,   36,  184,   28,  182,  166,
 /*   300 */   190,  181,  148,  149,  150,  182,  183,  190,  181,  175,
 /*   310 */    32,  176,  190,  183,  186,  190,  190,  190,  190,  184,
 /*   320 */    28,  190,  182,   51,  190,  181,  190,  190,  190,   31,
 /*   330 */   183,  190,  171,  182,   49,  190,  181,  190,  190,  134,
 /*   340 */    25,  183,  182,  145,  190,  181,  190,  190,  182,   54,
 /*   350 */   183,  181,  190,  190,  190,  190,  183,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    30,   31,    2,   42,    4,   46,    6,    7,    8,   48,
 /*    10 */    10,   11,   12,   13,   14,   15,   16,   17,   18,    0,
 /*    20 */    20,    2,   22,    4,   22,    6,    7,    8,   15,   10,
 /*    30 */    11,   12,   13,   14,   15,   16,    0,   18,    2,   20,
 /*    40 */     4,   22,    6,    7,    8,   46,   10,   11,   12,   13,
 /*    50 */    14,   15,   16,   46,   18,    7,    8,    7,   10,   23,
 /*    60 */    10,   46,    2,   15,    4,   15,    6,    7,    8,   42,
 /*    70 */    10,   11,   12,   13,   14,   15,   16,   10,   18,    6,
 /*    80 */     7,   32,   15,   10,   35,   25,   42,   27,   15,   16,
 /*    90 */     4,   46,    6,    7,    8,   46,   10,   11,   12,   13,
 /*   100 */    14,   15,   16,   42,   18,   20,   20,   22,   22,   48,
 /*   110 */     7,    8,   46,   10,   11,   12,   13,   29,   15,   42,
 /*   120 */    32,   33,   34,   35,   36,   48,   38,   39,   40,   41,
 /*   130 */    47,   43,    7,   45,   46,   10,    2,   42,    4,   47,
 /*   140 */     6,    7,    8,   48,   10,   11,   12,   13,   14,   15,
 /*   150 */    16,   30,   18,    7,    8,    0,   10,   11,   12,   13,
 /*   160 */    14,   15,   16,   20,   18,   28,   20,   35,   22,   26,
 /*   170 */    29,    6,    7,   32,   33,   34,   35,   36,   46,   47,
 /*   180 */    15,   16,   41,   14,   14,   44,   45,   46,   29,   14,
 /*   190 */    14,   32,   33,   34,   35,   36,   24,    5,   26,   32,
 /*   200 */    41,   14,   35,   29,   45,   46,   32,   33,   34,   35,
 /*   210 */    36,   14,   20,   46,    5,   41,    6,    7,   29,   45,
 /*   220 */    46,   32,   33,   34,   35,   36,   16,   14,   14,   20,
 /*   230 */    41,   14,   14,   29,   45,   46,   32,   33,   34,   35,
 /*   240 */    36,   14,   14,    4,    4,   41,    4,    4,   29,   45,
 /*   250 */    46,   32,   33,   34,   35,   36,    5,   25,   49,   49,
 /*   260 */    41,   49,   49,   29,   45,   46,   32,   33,   34,   35,
 /*   270 */    36,   49,   49,   49,   49,   41,   49,   49,   29,   45,
 /*   280 */    46,   32,   33,   34,   35,   36,   49,    6,    7,   49,
 /*   290 */    41,   10,   49,   49,   45,   46,   15,   16,    7,    8,
 /*   300 */    49,   10,   11,   12,   13,    7,   15,   49,   10,   28,
 /*   310 */     6,    7,   49,   15,   10,   49,   49,   49,   49,   15,
 /*   320 */    16,   49,    7,    8,   49,   10,   49,   49,   49,   14,
 /*   330 */    15,   49,   28,    7,    8,   49,   10,   49,   49,    4,
 /*   340 */    14,   15,    7,    8,   49,   10,   49,   49,    7,    8,
 /*   350 */    15,   10,   49,   49,   49,   49,   15,   49,   49,   49,
 /*   360 */    49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
 /*   370 */    49,   49,   49,   49,   49,   49,   49,   49,   29,   29,
 /*   380 */    29,   29,   29,   29,   29,   29,
};
#define YY_SHIFT_COUNT    (66)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (341)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    36,   60,    0,   19,   86,  134,  134,  134,  134,  134,
 /*    10 */   134,  146,   85,   85,   85,    2,    2,  103,  291,   50,
 /*    20 */   281,  304,   73,   73,   13,  315,  326,  335,  165,   48,
 /*    30 */    48,  341,  210,  210,  298,  298,  298,  298,  298,  125,
 /*    40 */   125,   67,   13,  143,  172,  192,  209,  155,  137,  169,
 /*    50 */   170,  175,  176,  187,  197,  213,  214,  217,  218,  227,
 /*    60 */   228,  239,  240,  242,  243,  251,  232,
};
#define YY_REDUCE_COUNT (42)
#define YY_REDUCE_MIN   (-41)
#define YY_REDUCE_MAX   (249)
static const short yy_reduce_ofst[] = {
 /*     0 */   141,   88,  159,  159,  159,  174,  189,  204,  219,  234,
 /*    10 */   249,  159,  159,  159,  159,  159,  159,   49,  167,  132,
 /*    20 */   -39,   61,   77,   95,  -30,  -41,   -1,    7,   27,    7,
 /*    30 */     7,   15,   44,   27,   45,   45,   45,   45,   66,   83,
 /*    40 */    92,    7,  121,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   188,  188,  188,  188,  220,  188,  188,  188,  188,  188,
 /*    10 */   188,  219,  199,  198,  194,  196,  197,  188,  188,  188,
 /*    20 */   188,  188,  188,  188,  205,  188,  188,  188,  188,  237,
 /*    30 */   241,  188,  188,  188,  234,  238,  210,  188,  188,  188,
 /*    40 */   188,  214,  204,  233,  188,  188,  188,  188,  188,  188,
 /*    50 */   188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
 /*    60 */   188,  255,  254,  256,  188,  188,  188,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  RSQueryParser_ARG_SDECL                /* A place to hold %extra_argument */
  RSQueryParser_CTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void RSQueryParser_Trace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "LOWEST",
  /*    2 */ "TILDE",
  /*    3 */ "TAGLIST",
  /*    4 */ "QUOTE",
  /*    5 */ "COLON",
  /*    6 */ "MINUS",
  /*    7 */ "NUMBER",
  /*    8 */ "STOPWORD",
  /*    9 */ "TERMLIST",
  /*   10 */ "TERM",
  /*   11 */ "PREFIX",
  /*   12 */ "SUFFIX",
  /*   13 */ "CONTAINS",
  /*   14 */ "PERCENT",
  /*   15 */ "ATTRIBUTE",
  /*   16 */ "LP",
  /*   17 */ "RP",
  /*   18 */ "MODIFIER",
  /*   19 */ "AND",
  /*   20 */ "OR",
  /*   21 */ "ORX",
  /*   22 */ "ARROW",
  /*   23 */ "STAR",
  /*   24 */ "SEMICOLON",
  /*   25 */ "LB",
  /*   26 */ "RB",
  /*   27 */ "LSQB",
  /*   28 */ "RSQB",
  /*   29 */ "expr",
  /*   30 */ "attribute",
  /*   31 */ "attribute_list",
  /*   32 */ "prefix",
  /*   33 */ "suffix",
  /*   34 */ "contains",
  /*   35 */ "termlist",
  /*   36 */ "union",
  /*   37 */ "fuzzy",
  /*   38 */ "tag_list",
  /*   39 */ "geo_filter",
  /*   40 */ "vector_filter",
  /*   41 */ "modifierlist",
  /*   42 */ "num",
  /*   43 */ "numeric_range",
  /*   44 */ "query",
  /*   45 */ "modifier",
  /*   46 */ "param_term",
  /*   47 */ "term",
  /*   48 */ "param_any",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "query ::= expr",
 /*   1 */ "query ::=",
 /*   2 */ "query ::= STAR",
 /*   3 */ "expr ::= expr expr",
 /*   4 */ "expr ::= union",
 /*   5 */ "union ::= expr OR expr",
 /*   6 */ "union ::= union OR expr",
 /*   7 */ "expr ::= modifier COLON expr",
 /*   8 */ "expr ::= modifierlist COLON expr",
 /*   9 */ "expr ::= LP expr RP",
 /*  10 */ "attribute ::= ATTRIBUTE COLON param_term",
 /*  11 */ "attribute_list ::= attribute",
 /*  12 */ "attribute_list ::= attribute_list SEMICOLON attribute",
 /*  13 */ "attribute_list ::= attribute_list SEMICOLON",
 /*  14 */ "attribute_list ::=",
 /*  15 */ "expr ::= expr ARROW LB attribute_list RB",
 /*  16 */ "expr ::= QUOTE termlist QUOTE",
 /*  17 */ "expr ::= QUOTE term QUOTE",
 /*  18 */ "expr ::= QUOTE ATTRIBUTE QUOTE",
 /*  19 */ "expr ::= param_term",
 /*  20 */ "expr ::= prefix",
 /*  21 */ "expr ::= suffix",
 /*  22 */ "expr ::= contains",
 /*  23 */ "expr ::= termlist",
 /*  24 */ "expr ::= STOPWORD",
 /*  25 */ "termlist ::= param_term param_term",
 /*  26 */ "termlist ::= termlist param_term",
 /*  27 */ "termlist ::= termlist STOPWORD",
 /*  28 */ "expr ::= MINUS expr",
 /*  29 */ "expr ::= TILDE expr",
 /*  30 */ "prefix ::= PREFIX",
 /*  31 */ "prefix ::= SUFFIX",
 /*  32 */ "prefix ::= CONTAINS",
 /*  33 */ "expr ::= PERCENT param_term PERCENT",
 /*  34 */ "expr ::= PERCENT PERCENT param_term PERCENT PERCENT",
 /*  35 */ "expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT",
 /*  36 */ "expr ::= PERCENT STOPWORD PERCENT",
 /*  37 */ "expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT",
 /*  38 */ "expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT",
 /*  39 */ "modifier ::= MODIFIER",
 /*  40 */ "modifierlist ::= modifier OR term",
 /*  41 */ "modifierlist ::= modifierlist OR term",
 /*  42 */ "expr ::= modifier COLON tag_list",
 /*  43 */ "tag_list ::= LB param_term",
 /*  44 */ "tag_list ::= LB STOPWORD",
 /*  45 */ "tag_list ::= LB prefix",
 /*  46 */ "tag_list ::= LB termlist",
 /*  47 */ "tag_list ::= tag_list OR param_term",
 /*  48 */ "tag_list ::= tag_list OR STOPWORD",
 /*  49 */ "tag_list ::= tag_list OR prefix",
 /*  50 */ "tag_list ::= tag_list OR termlist",
 /*  51 */ "tag_list ::= tag_list RB",
 /*  52 */ "expr ::= modifier COLON numeric_range",
 /*  53 */ "numeric_range ::= LSQB param_any param_any RSQB",
 /*  54 */ "expr ::= modifier COLON geo_filter",
 /*  55 */ "geo_filter ::= LSQB param_any param_any param_any param_any RSQB",
 /*  56 */ "expr ::= modifier COLON vector_filter",
 /*  57 */ "vector_filter ::= LSQB param_any param_any param_any RSQB",
 /*  58 */ "num ::= NUMBER",
 /*  59 */ "num ::= LP num",
 /*  60 */ "num ::= MINUS num",
 /*  61 */ "term ::= TERM",
 /*  62 */ "term ::= NUMBER",
 /*  63 */ "param_term ::= TERM",
 /*  64 */ "param_term ::= NUMBER",
 /*  65 */ "param_term ::= ATTRIBUTE",
 /*  66 */ "param_any ::= ATTRIBUTE",
 /*  67 */ "param_any ::= LP ATTRIBUTE",
 /*  68 */ "param_any ::= TERM",
 /*  69 */ "param_any ::= num",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to RSQueryParser_Alloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void RSQueryParser_Init(void *yypRawParser RSQueryParser_CTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  RSQueryParser_CTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef RSQueryParser__ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to RSQueryParser_ and RSQueryParser_Free.
*/
void *RSQueryParser_Alloc(void *(*mallocProc)(YYMALLOCARGTYPE) RSQueryParser_CTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    RSQueryParser_CTX_STORE
    RSQueryParser_Init(yypParser RSQueryParser_CTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* RSQueryParser__ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  RSQueryParser_ARG_FETCH
  RSQueryParser_CTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* Default NON-TERMINAL Destructor */
    case 42: /* num */
    case 44: /* query */
    case 45: /* modifier */
    case 46: /* param_term */
    case 47: /* term */
    case 48: /* param_any */
{
 
}
      break;
    case 29: /* expr */
    case 32: /* prefix */
    case 33: /* suffix */
    case 34: /* contains */
    case 35: /* termlist */
    case 36: /* union */
    case 37: /* fuzzy */
    case 38: /* tag_list */
{
 QueryNode_Free((yypminor->yy21)); 
}
      break;
    case 30: /* attribute */
{
 rm_free((char*)(yypminor->yy13).value); 
}
      break;
    case 31: /* attribute_list */
{
 array_free_ex((yypminor->yy14), rm_free((char*)((QueryAttribute*)ptr )->value)); 
}
      break;
    case 39: /* geo_filter */
    case 40: /* vector_filter */
{
 QueryParam_Free((yypminor->yy22)); 
}
      break;
    case 41: /* modifierlist */
{
 
    for (size_t i = 0; i < Vector_Size((yypminor->yy64)); i++) {
        char *s;
        Vector_Get((yypminor->yy64), i, &s);
        rm_free(s);
    }
    Vector_Free((yypminor->yy64)); 

}
      break;
    case 43: /* numeric_range */
{

  QueryParam_Free((yypminor->yy22));

}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void RSQueryParser_Finalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef RSQueryParser__ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void RSQueryParser_Free(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  RSQueryParser_Finalize(p);
  (*freeProc)(p);
}
#endif /* RSQueryParser__ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int RSQueryParser_StackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int RSQueryParser_Coverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   RSQueryParser_ARG_FETCH
   RSQueryParser_CTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   RSQueryParser_ARG_STORE /* Suppress warning about unused %extra_argument var */
   RSQueryParser_CTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  RSQueryParser_TOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    44,  /* (0) query ::= expr */
    44,  /* (1) query ::= */
    44,  /* (2) query ::= STAR */
    29,  /* (3) expr ::= expr expr */
    29,  /* (4) expr ::= union */
    36,  /* (5) union ::= expr OR expr */
    36,  /* (6) union ::= union OR expr */
    29,  /* (7) expr ::= modifier COLON expr */
    29,  /* (8) expr ::= modifierlist COLON expr */
    29,  /* (9) expr ::= LP expr RP */
    30,  /* (10) attribute ::= ATTRIBUTE COLON param_term */
    31,  /* (11) attribute_list ::= attribute */
    31,  /* (12) attribute_list ::= attribute_list SEMICOLON attribute */
    31,  /* (13) attribute_list ::= attribute_list SEMICOLON */
    31,  /* (14) attribute_list ::= */
    29,  /* (15) expr ::= expr ARROW LB attribute_list RB */
    29,  /* (16) expr ::= QUOTE termlist QUOTE */
    29,  /* (17) expr ::= QUOTE term QUOTE */
    29,  /* (18) expr ::= QUOTE ATTRIBUTE QUOTE */
    29,  /* (19) expr ::= param_term */
    29,  /* (20) expr ::= prefix */
    29,  /* (21) expr ::= suffix */
    29,  /* (22) expr ::= contains */
    29,  /* (23) expr ::= termlist */
    29,  /* (24) expr ::= STOPWORD */
    35,  /* (25) termlist ::= param_term param_term */
    35,  /* (26) termlist ::= termlist param_term */
    35,  /* (27) termlist ::= termlist STOPWORD */
    29,  /* (28) expr ::= MINUS expr */
    29,  /* (29) expr ::= TILDE expr */
    32,  /* (30) prefix ::= PREFIX */
    32,  /* (31) prefix ::= SUFFIX */
    32,  /* (32) prefix ::= CONTAINS */
    29,  /* (33) expr ::= PERCENT param_term PERCENT */
    29,  /* (34) expr ::= PERCENT PERCENT param_term PERCENT PERCENT */
    29,  /* (35) expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT */
    29,  /* (36) expr ::= PERCENT STOPWORD PERCENT */
    29,  /* (37) expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT */
    29,  /* (38) expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT */
    45,  /* (39) modifier ::= MODIFIER */
    41,  /* (40) modifierlist ::= modifier OR term */
    41,  /* (41) modifierlist ::= modifierlist OR term */
    29,  /* (42) expr ::= modifier COLON tag_list */
    38,  /* (43) tag_list ::= LB param_term */
    38,  /* (44) tag_list ::= LB STOPWORD */
    38,  /* (45) tag_list ::= LB prefix */
    38,  /* (46) tag_list ::= LB termlist */
    38,  /* (47) tag_list ::= tag_list OR param_term */
    38,  /* (48) tag_list ::= tag_list OR STOPWORD */
    38,  /* (49) tag_list ::= tag_list OR prefix */
    38,  /* (50) tag_list ::= tag_list OR termlist */
    38,  /* (51) tag_list ::= tag_list RB */
    29,  /* (52) expr ::= modifier COLON numeric_range */
    43,  /* (53) numeric_range ::= LSQB param_any param_any RSQB */
    29,  /* (54) expr ::= modifier COLON geo_filter */
    39,  /* (55) geo_filter ::= LSQB param_any param_any param_any param_any RSQB */
    29,  /* (56) expr ::= modifier COLON vector_filter */
    40,  /* (57) vector_filter ::= LSQB param_any param_any param_any RSQB */
    42,  /* (58) num ::= NUMBER */
    42,  /* (59) num ::= LP num */
    42,  /* (60) num ::= MINUS num */
    47,  /* (61) term ::= TERM */
    47,  /* (62) term ::= NUMBER */
    46,  /* (63) param_term ::= TERM */
    46,  /* (64) param_term ::= NUMBER */
    46,  /* (65) param_term ::= ATTRIBUTE */
    48,  /* (66) param_any ::= ATTRIBUTE */
    48,  /* (67) param_any ::= LP ATTRIBUTE */
    48,  /* (68) param_any ::= TERM */
    48,  /* (69) param_any ::= num */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) query ::= expr */
    0,  /* (1) query ::= */
   -1,  /* (2) query ::= STAR */
   -2,  /* (3) expr ::= expr expr */
   -1,  /* (4) expr ::= union */
   -3,  /* (5) union ::= expr OR expr */
   -3,  /* (6) union ::= union OR expr */
   -3,  /* (7) expr ::= modifier COLON expr */
   -3,  /* (8) expr ::= modifierlist COLON expr */
   -3,  /* (9) expr ::= LP expr RP */
   -3,  /* (10) attribute ::= ATTRIBUTE COLON param_term */
   -1,  /* (11) attribute_list ::= attribute */
   -3,  /* (12) attribute_list ::= attribute_list SEMICOLON attribute */
   -2,  /* (13) attribute_list ::= attribute_list SEMICOLON */
    0,  /* (14) attribute_list ::= */
   -5,  /* (15) expr ::= expr ARROW LB attribute_list RB */
   -3,  /* (16) expr ::= QUOTE termlist QUOTE */
   -3,  /* (17) expr ::= QUOTE term QUOTE */
   -3,  /* (18) expr ::= QUOTE ATTRIBUTE QUOTE */
   -1,  /* (19) expr ::= param_term */
   -1,  /* (20) expr ::= prefix */
   -1,  /* (21) expr ::= suffix */
   -1,  /* (22) expr ::= contains */
   -1,  /* (23) expr ::= termlist */
   -1,  /* (24) expr ::= STOPWORD */
   -2,  /* (25) termlist ::= param_term param_term */
   -2,  /* (26) termlist ::= termlist param_term */
   -2,  /* (27) termlist ::= termlist STOPWORD */
   -2,  /* (28) expr ::= MINUS expr */
   -2,  /* (29) expr ::= TILDE expr */
   -1,  /* (30) prefix ::= PREFIX */
   -1,  /* (31) prefix ::= SUFFIX */
   -1,  /* (32) prefix ::= CONTAINS */
   -3,  /* (33) expr ::= PERCENT param_term PERCENT */
   -5,  /* (34) expr ::= PERCENT PERCENT param_term PERCENT PERCENT */
   -7,  /* (35) expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT */
   -3,  /* (36) expr ::= PERCENT STOPWORD PERCENT */
   -5,  /* (37) expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT */
   -7,  /* (38) expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT */
   -1,  /* (39) modifier ::= MODIFIER */
   -3,  /* (40) modifierlist ::= modifier OR term */
   -3,  /* (41) modifierlist ::= modifierlist OR term */
   -3,  /* (42) expr ::= modifier COLON tag_list */
   -2,  /* (43) tag_list ::= LB param_term */
   -2,  /* (44) tag_list ::= LB STOPWORD */
   -2,  /* (45) tag_list ::= LB prefix */
   -2,  /* (46) tag_list ::= LB termlist */
   -3,  /* (47) tag_list ::= tag_list OR param_term */
   -3,  /* (48) tag_list ::= tag_list OR STOPWORD */
   -3,  /* (49) tag_list ::= tag_list OR prefix */
   -3,  /* (50) tag_list ::= tag_list OR termlist */
   -2,  /* (51) tag_list ::= tag_list RB */
   -3,  /* (52) expr ::= modifier COLON numeric_range */
   -4,  /* (53) numeric_range ::= LSQB param_any param_any RSQB */
   -3,  /* (54) expr ::= modifier COLON geo_filter */
   -6,  /* (55) geo_filter ::= LSQB param_any param_any param_any param_any RSQB */
   -3,  /* (56) expr ::= modifier COLON vector_filter */
   -5,  /* (57) vector_filter ::= LSQB param_any param_any param_any RSQB */
   -1,  /* (58) num ::= NUMBER */
   -2,  /* (59) num ::= LP num */
   -2,  /* (60) num ::= MINUS num */
   -1,  /* (61) term ::= TERM */
   -1,  /* (62) term ::= NUMBER */
   -1,  /* (63) param_term ::= TERM */
   -1,  /* (64) param_term ::= NUMBER */
   -1,  /* (65) param_term ::= ATTRIBUTE */
   -1,  /* (66) param_any ::= ATTRIBUTE */
   -2,  /* (67) param_any ::= LP ATTRIBUTE */
   -1,  /* (68) param_any ::= TERM */
   -1,  /* (69) param_any ::= num */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  RSQueryParser_TOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  RSQueryParser_CTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  RSQueryParser_ARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* query ::= expr */
{ 
  setup_trace(ctx);
  ctx->root = yymsp[0].minor.yy21;
 
}
        break;
      case 1: /* query ::= */
{
  ctx->root = NULL;
}
        break;
      case 2: /* query ::= STAR */
{
  setup_trace(ctx);
  ctx->root = NewWildcardNode();
}
        break;
      case 3: /* expr ::= expr expr */
{
    int rv = one_not_null(yymsp[-1].minor.yy21, yymsp[0].minor.yy21, (void**)&yylhsminor.yy21);
    if (rv == NODENN_BOTH_INVALID) {
        yylhsminor.yy21 = NULL;
    } else if (rv == NODENN_ONE_NULL) {
        // Nothing- `out` is already assigned
    } else {
        if (yymsp[-1].minor.yy21 && yymsp[-1].minor.yy21->type == QN_PHRASE && yymsp[-1].minor.yy21->pn.exact == 0 && 
            yymsp[-1].minor.yy21->opts.fieldMask == RS_FIELDMASK_ALL ) {
            yylhsminor.yy21 = yymsp[-1].minor.yy21;
        } else {     
            yylhsminor.yy21 = NewPhraseNode(0);
            QueryNode_AddChild(yylhsminor.yy21, yymsp[-1].minor.yy21);
        }
        QueryNode_AddChild(yylhsminor.yy21, yymsp[0].minor.yy21);
    }
}
  yymsp[-1].minor.yy21 = yylhsminor.yy21;
        break;
      case 4: /* expr ::= union */
      case 20: /* expr ::= prefix */ yytestcase(yyruleno==20);
      case 21: /* expr ::= suffix */ yytestcase(yyruleno==21);
      case 22: /* expr ::= contains */ yytestcase(yyruleno==22);
{
    yylhsminor.yy21 = yymsp[0].minor.yy21;
}
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 5: /* union ::= expr OR expr */
{
    int rv = one_not_null(yymsp[-2].minor.yy21, yymsp[0].minor.yy21, (void**)&yylhsminor.yy21);
    if (rv == NODENN_BOTH_INVALID) {
        yylhsminor.yy21 = NULL;
    } else if (rv == NODENN_ONE_NULL) {
        // Nothing- already assigned
    } else {
        if (yymsp[-2].minor.yy21->type == QN_UNION && yymsp[-2].minor.yy21->opts.fieldMask == RS_FIELDMASK_ALL) {
            yylhsminor.yy21 = yymsp[-2].minor.yy21;
        } else {
            yylhsminor.yy21 = NewUnionNode();
            QueryNode_AddChild(yylhsminor.yy21, yymsp[-2].minor.yy21);
            yylhsminor.yy21->opts.fieldMask |= yymsp[-2].minor.yy21->opts.fieldMask;
        }

        // Handle yymsp[0].minor.yy21
        QueryNode_AddChild(yylhsminor.yy21, yymsp[0].minor.yy21);
        yylhsminor.yy21->opts.fieldMask |= yymsp[0].minor.yy21->opts.fieldMask;
        QueryNode_SetFieldMask(yylhsminor.yy21, yylhsminor.yy21->opts.fieldMask);
    }
    
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 6: /* union ::= union OR expr */
{
    yylhsminor.yy21 = yymsp[-2].minor.yy21;
    if (yymsp[0].minor.yy21) {
        QueryNode_AddChild(yylhsminor.yy21, yymsp[0].minor.yy21);
        yylhsminor.yy21->opts.fieldMask |= yymsp[0].minor.yy21->opts.fieldMask;
        QueryNode_SetFieldMask(yymsp[0].minor.yy21, yylhsminor.yy21->opts.fieldMask);
    }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 7: /* expr ::= modifier COLON expr */
{
    if (yymsp[0].minor.yy21 == NULL) {
        yylhsminor.yy21 = NULL;
    } else {
        if (ctx->sctx->spec) {
            QueryNode_SetFieldMask(yymsp[0].minor.yy21, IndexSpec_GetFieldBit(ctx->sctx->spec, yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len));
        }
        yylhsminor.yy21 = yymsp[0].minor.yy21; 
    }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 8: /* expr ::= modifierlist COLON expr */
{
    
    if (yymsp[0].minor.yy21 == NULL) {
        yylhsminor.yy21 = NULL;
    } else {
        //yymsp[0].minor.yy21->opts.fieldMask = 0;
        t_fieldMask mask = 0; 
        if (ctx->sctx->spec) {
            for (int i = 0; i < Vector_Size(yymsp[-2].minor.yy64); i++) {
                char *p;
                Vector_Get(yymsp[-2].minor.yy64, i, &p);
                mask |= IndexSpec_GetFieldBit(ctx->sctx->spec, p, strlen(p)); 
                rm_free(p);
            }
        }
        QueryNode_SetFieldMask(yymsp[0].minor.yy21, mask);
        Vector_Free(yymsp[-2].minor.yy64);
        yylhsminor.yy21=yymsp[0].minor.yy21;
    }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 9: /* expr ::= LP expr RP */
{
    yymsp[-2].minor.yy21 = yymsp[-1].minor.yy21;
}
        break;
      case 10: /* attribute ::= ATTRIBUTE COLON param_term */
{
  const char *value = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
  size_t value_len = yymsp[0].minor.yy0.len;
  if (yymsp[0].minor.yy0.type == QT_PARAM_TERM) {
    size_t found_value_len;
    const char *found_value = Param_DictGet(ctx->opts->params, value, &found_value_len, ctx->status);
    if (found_value) {
      rm_free((char*)value);
      value = rm_strndup(found_value, found_value_len);
      value_len = found_value_len;
    }
  }
  yylhsminor.yy13 = (QueryAttribute){ .name = yymsp[-2].minor.yy0.s, .namelen = yymsp[-2].minor.yy0.len, .value = value, .vallen = value_len };
}
  yymsp[-2].minor.yy13 = yylhsminor.yy13;
        break;
      case 11: /* attribute_list ::= attribute */
{
  yylhsminor.yy14 = array_new(QueryAttribute, 2);
  yylhsminor.yy14 = array_append(yylhsminor.yy14, yymsp[0].minor.yy13);
}
  yymsp[0].minor.yy14 = yylhsminor.yy14;
        break;
      case 12: /* attribute_list ::= attribute_list SEMICOLON attribute */
{
  yylhsminor.yy14 = array_append(yymsp[-2].minor.yy14, yymsp[0].minor.yy13);
}
  yymsp[-2].minor.yy14 = yylhsminor.yy14;
        break;
      case 13: /* attribute_list ::= attribute_list SEMICOLON */
{
    yylhsminor.yy14 = yymsp[-1].minor.yy14;
}
  yymsp[-1].minor.yy14 = yylhsminor.yy14;
        break;
      case 14: /* attribute_list ::= */
{
    yymsp[1].minor.yy14 = NULL;
}
        break;
      case 15: /* expr ::= expr ARROW LB attribute_list RB */
{

    if (yymsp[-4].minor.yy21 && yymsp[-1].minor.yy14) {
        QueryNode_ApplyAttributes(yymsp[-4].minor.yy21, yymsp[-1].minor.yy14, array_len(yymsp[-1].minor.yy14), ctx->status);
    }
    array_free_ex(yymsp[-1].minor.yy14, rm_free((char*)((QueryAttribute*)ptr )->value));
    yylhsminor.yy21 = yymsp[-4].minor.yy21;
}
  yymsp[-4].minor.yy21 = yylhsminor.yy21;
        break;
      case 16: /* expr ::= QUOTE termlist QUOTE */
{
  // TODO: Quoted/verbatim string in termlist should not be handled as parameters
  // Also need to add the leading '$' which was consumed by the lexer
  yymsp[-1].minor.yy21->pn.exact = 1;
  yymsp[-1].minor.yy21->opts.flags |= QueryNode_Verbatim;

  yymsp[-2].minor.yy21 = yymsp[-1].minor.yy21;
}
        break;
      case 17: /* expr ::= QUOTE term QUOTE */
{
  yymsp[-2].minor.yy21 = NewTokenNode(ctx, rm_strdupcase(yymsp[-1].minor.yy0.s, yymsp[-1].minor.yy0.len), -1);
  yymsp[-2].minor.yy21->opts.flags |= QueryNode_Verbatim;
}
        break;
      case 18: /* expr ::= QUOTE ATTRIBUTE QUOTE */
{
  // Quoted/verbatim string should not be handled as parameters
  // Also need to add the leading '$' which was consumed by the lexer
  char *s = rm_malloc(yymsp[-1].minor.yy0.len + 1);
  *s = '$';
  memcpy(s + 1, yymsp[-1].minor.yy0.s, yymsp[-1].minor.yy0.len);
  yymsp[-2].minor.yy21 = NewTokenNode(ctx, rm_strdupcase(s, yymsp[-1].minor.yy0.len + 1), -1);
  rm_free(s);
  yymsp[-2].minor.yy21->opts.flags |= QueryNode_Verbatim;
}
        break;
      case 19: /* expr ::= param_term */
{
  yylhsminor.yy21 = NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0);
}
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 23: /* expr ::= termlist */
{
        yylhsminor.yy21 = yymsp[0].minor.yy21;
}
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 24: /* expr ::= STOPWORD */
{
    yymsp[0].minor.yy21 = NULL;
}
        break;
      case 25: /* termlist ::= param_term param_term */
{
  yylhsminor.yy21 = NewPhraseNode(0);
  QueryNode_AddChild(yylhsminor.yy21, NewTokenNode_WithParams(ctx, &yymsp[-1].minor.yy0));
  QueryNode_AddChild(yylhsminor.yy21, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
}
  yymsp[-1].minor.yy21 = yylhsminor.yy21;
        break;
      case 26: /* termlist ::= termlist param_term */
{
  yylhsminor.yy21 = yymsp[-1].minor.yy21;
  QueryNode_AddChild(yylhsminor.yy21, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
}
  yymsp[-1].minor.yy21 = yylhsminor.yy21;
        break;
      case 27: /* termlist ::= termlist STOPWORD */
      case 51: /* tag_list ::= tag_list RB */ yytestcase(yyruleno==51);
{
    yylhsminor.yy21 = yymsp[-1].minor.yy21;
}
  yymsp[-1].minor.yy21 = yylhsminor.yy21;
        break;
      case 28: /* expr ::= MINUS expr */
{ 
    if (yymsp[0].minor.yy21) {
        yymsp[-1].minor.yy21 = NewNotNode(yymsp[0].minor.yy21);
    } else {
        yymsp[-1].minor.yy21 = NULL;
    }
}
        break;
      case 29: /* expr ::= TILDE expr */
{ 
    if (yymsp[0].minor.yy21) {
        yymsp[-1].minor.yy21 = NewOptionalNode(yymsp[0].minor.yy21);
    } else {
        yymsp[-1].minor.yy21 = NULL;
    }
}
        break;
      case 30: /* prefix ::= PREFIX */
{
    yylhsminor.yy21 = NewPrefixNode_WithParams(ctx, &yymsp[0].minor.yy0, true, false);
}
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 31: /* prefix ::= SUFFIX */
{
    yylhsminor.yy21 = NewPrefixNode_WithParams(ctx, &yymsp[0].minor.yy0, false, true);
}
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 32: /* prefix ::= CONTAINS */
{
    yylhsminor.yy21 = NewPrefixNode_WithParams(ctx, &yymsp[0].minor.yy0, true, true);
}
  yymsp[0].minor.yy21 = yylhsminor.yy21;
        break;
      case 33: /* expr ::= PERCENT param_term PERCENT */
      case 36: /* expr ::= PERCENT STOPWORD PERCENT */ yytestcase(yyruleno==36);
{
  yymsp[-2].minor.yy21 = NewFuzzyNode_WithParams(ctx, &yymsp[-1].minor.yy0, 1);
}
        break;
      case 34: /* expr ::= PERCENT PERCENT param_term PERCENT PERCENT */
      case 37: /* expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT */ yytestcase(yyruleno==37);
{
  yymsp[-4].minor.yy21 = NewFuzzyNode_WithParams(ctx, &yymsp[-2].minor.yy0, 2);
}
        break;
      case 35: /* expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT */
      case 38: /* expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT */ yytestcase(yyruleno==38);
{
  yymsp[-6].minor.yy21 = NewFuzzyNode_WithParams(ctx, &yymsp[-3].minor.yy0, 3);
}
        break;
      case 39: /* modifier ::= MODIFIER */
{
    yymsp[0].minor.yy0.len = unescapen((char*)yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
    yylhsminor.yy0 = yymsp[0].minor.yy0;
 }
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 40: /* modifierlist ::= modifier OR term */
{
    yylhsminor.yy64 = NewVector(char *, 2);
    char *s = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
    Vector_Push(yylhsminor.yy64, s);
    s = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
    Vector_Push(yylhsminor.yy64, s);
}
  yymsp[-2].minor.yy64 = yylhsminor.yy64;
        break;
      case 41: /* modifierlist ::= modifierlist OR term */
{
    char *s = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
    Vector_Push(yymsp[-2].minor.yy64, s);
    yylhsminor.yy64 = yymsp[-2].minor.yy64;
}
  yymsp[-2].minor.yy64 = yylhsminor.yy64;
        break;
      case 42: /* expr ::= modifier COLON tag_list */
{
    if (!yymsp[0].minor.yy21) {
        yylhsminor.yy21= NULL;
    } else {
      // Tag field names must be case sensitive, we can't do rm_strdupcase
        char *s = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
        size_t slen = unescapen((char*)s, yymsp[-2].minor.yy0.len);

        yylhsminor.yy21 = NewTagNode(s, slen);
        QueryNode_AddChildren(yylhsminor.yy21, yymsp[0].minor.yy21->children, QueryNode_NumChildren(yymsp[0].minor.yy21));
        
        // Set the children count on yymsp[0].minor.yy21 to 0 so they won't get recursively free'd
        QueryNode_ClearChildren(yymsp[0].minor.yy21, 0);
        QueryNode_Free(yymsp[0].minor.yy21);
    }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 43: /* tag_list ::= LB param_term */
{
  yymsp[-1].minor.yy21 = NewPhraseNode(0);
  if (yymsp[0].minor.yy0.type == QT_TERM)
    yymsp[0].minor.yy0.type = QT_TERM_CASE;
  else if (yymsp[0].minor.yy0.type == QT_PARAM_TERM)
    yymsp[0].minor.yy0.type = QT_PARAM_TERM_CASE;
  QueryNode_AddChild(yymsp[-1].minor.yy21, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
}
        break;
      case 44: /* tag_list ::= LB STOPWORD */
{
    yymsp[-1].minor.yy21 = NewPhraseNode(0);
    QueryNode_AddChild(yymsp[-1].minor.yy21, NewTokenNode(ctx, rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len), -1));
}
        break;
      case 45: /* tag_list ::= LB prefix */
      case 46: /* tag_list ::= LB termlist */ yytestcase(yyruleno==46);
{
    yymsp[-1].minor.yy21 = NewPhraseNode(0);
    QueryNode_AddChild(yymsp[-1].minor.yy21, yymsp[0].minor.yy21);
}
        break;
      case 47: /* tag_list ::= tag_list OR param_term */
{
  if (yymsp[0].minor.yy0.type == QT_TERM)
    yymsp[0].minor.yy0.type = QT_TERM_CASE;
  else if (yymsp[0].minor.yy0.type == QT_PARAM_TERM)
    yymsp[0].minor.yy0.type = QT_PARAM_TERM_CASE;
  QueryNode_AddChild(yymsp[-2].minor.yy21, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
  yylhsminor.yy21 = yymsp[-2].minor.yy21;
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 48: /* tag_list ::= tag_list OR STOPWORD */
{
    QueryNode_AddChild(yymsp[-2].minor.yy21, NewTokenNode(ctx, rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len), -1));
    yylhsminor.yy21 = yymsp[-2].minor.yy21;
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 49: /* tag_list ::= tag_list OR prefix */
      case 50: /* tag_list ::= tag_list OR termlist */ yytestcase(yyruleno==50);
{
    QueryNode_AddChild(yymsp[-2].minor.yy21, yymsp[0].minor.yy21);
    yylhsminor.yy21 = yymsp[-2].minor.yy21;
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 52: /* expr ::= modifier COLON numeric_range */
{
  if (yymsp[0].minor.yy22) {
    // we keep the capitalization as is
    yymsp[0].minor.yy22->nf->fieldName = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
    yylhsminor.yy21 = NewNumericNode(yymsp[0].minor.yy22);
  } else {
    yylhsminor.yy21 = NewQueryNode(QN_NULL);
  }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 53: /* numeric_range ::= LSQB param_any param_any RSQB */
{
  // Update token type to be more specific if possible
  // and detect syntax errors
  QueryToken *badToken = NULL;
  if (yymsp[-2].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-2].minor.yy0.type = QT_PARAM_NUMERIC_MIN_RANGE;
  else if (yymsp[-2].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-2].minor.yy0;
  if (yymsp[-1].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-1].minor.yy0.type = QT_PARAM_NUMERIC_MAX_RANGE;
  else if (!badToken && yymsp[-1].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-1].minor.yy0;

  if (!badToken) {
    yymsp[-3].minor.yy22 = NewNumericFilterQueryParam_WithParams(ctx, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0, yymsp[-2].minor.yy0.inclusive, yymsp[-1].minor.yy0.inclusive);
  } else {
    reportSyntaxError(ctx->status, badToken, "Expecting numeric or parameter");
    yymsp[-3].minor.yy22 = NULL;
  }
}
        break;
      case 54: /* expr ::= modifier COLON geo_filter */
{
  if (yymsp[0].minor.yy22) {
    // we keep the capitalization as is
    yymsp[0].minor.yy22->gf->property = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
    yylhsminor.yy21 = NewGeofilterNode(yymsp[0].minor.yy22);
  } else {
    yylhsminor.yy21 = NewQueryNode(QN_NULL);
  }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 55: /* geo_filter ::= LSQB param_any param_any param_any param_any RSQB */
{
  // Update token type to be more specific if possible
  // and detect syntax errors
  QueryToken *badToken = NULL;

  if (yymsp[-4].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-4].minor.yy0.type = QT_PARAM_GEO_COORD;
  else if (yymsp[-4].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-4].minor.yy0;
  if (yymsp[-3].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-3].minor.yy0.type = QT_PARAM_GEO_COORD;
  else if (!badToken && yymsp[-3].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-3].minor.yy0;
  if (yymsp[-2].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-2].minor.yy0.type = QT_PARAM_NUMERIC;
  else if (!badToken && yymsp[-2].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-2].minor.yy0;
  if (yymsp[-1].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-1].minor.yy0.type = QT_PARAM_GEO_UNIT;
  else if (!badToken && yymsp[-1].minor.yy0.type != QT_TERM)
    badToken = &yymsp[-1].minor.yy0;

  if (!badToken) {
    yymsp[-5].minor.yy22 = NewGeoFilterQueryParam_WithParams(ctx, &yymsp[-4].minor.yy0, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0);
  } else {
    reportSyntaxError(ctx->status, badToken, "Syntax error");
    yymsp[-5].minor.yy22 = NULL;
  }
}
        break;
      case 56: /* expr ::= modifier COLON vector_filter */
{
  // we keep the capitalization as is
  if (yymsp[0].minor.yy22) {
      yymsp[0].minor.yy22->vf->property = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
      yylhsminor.yy21 = NewVectorNode(yymsp[0].minor.yy22);
  } else {
      yylhsminor.yy21 = NewQueryNode(QN_NULL);
  }
}
  yymsp[-2].minor.yy21 = yylhsminor.yy21;
        break;
      case 57: /* vector_filter ::= LSQB param_any param_any param_any RSQB */
{
  // Update token types to be more specific if possible
  // and detect syntax errors
  QueryToken *badToken = NULL;
  if (yymsp[-3].minor.yy0.type == QT_TERM) {
    yymsp[-3].minor.yy0.type = QT_VEC;
    // FIXME: Remove hack for handling lexer/scanner of terms with trailing equal signs.
    //  Equal signs are currently considered as punct (punctuation) and are not included in a
    //  term, But in base64 encoding, it is used as padding to extend the string to a length
    //  which is a multiple of 3.
    size_t len = yymsp[-3].minor.yy0.len;
    int remainder = len % 3;
    if (remainder == 1 && *((yymsp[-3].minor.yy0.s) + len) == '=' && *((yymsp[-3].minor.yy0.s) + len + 1) == '=')
      yymsp[-3].minor.yy0.len = len + 2;
    else if (remainder == 2 && *((yymsp[-3].minor.yy0.s) + len) == '=')
      yymsp[-3].minor.yy0.len = len + 1;
  } else if (yymsp[-3].minor.yy0.type == QT_PARAM_ANY) {
    yymsp[-3].minor.yy0.type = QT_PARAM_VEC;
  } else {
    badToken = &yymsp[-3].minor.yy0;
  }

  if (yymsp[-2].minor.yy0.type == QT_PARAM_ANY) {
    yymsp[-2].minor.yy0.type = QT_PARAM_VEC_SIM_TYPE;
  } else if (!badToken && yymsp[-2].minor.yy0.type != QT_TERM) {
    badToken = &yymsp[-2].minor.yy0;
  }

  if (yymsp[-1].minor.yy0.type == QT_PARAM_ANY) {
    yymsp[-1].minor.yy0.type = QT_PARAM_NUMERIC;
  } else if (!badToken && yymsp[-1].minor.yy0.type != QT_NUMERIC) {
    badToken = &yymsp[-1].minor.yy0;
  }

  if (!badToken) {
    yymsp[-4].minor.yy22 = NewVectorFilterQueryParam_WithParams(ctx, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0);
  } else {
    reportSyntaxError(ctx->status, badToken, "Syntax error");
    yymsp[-4].minor.yy22 = NULL;
  }
}
        break;
      case 58: /* num ::= NUMBER */
{
    yylhsminor.yy83.num = yymsp[0].minor.yy0.numval;
    yylhsminor.yy83.inclusive = 1;
}
  yymsp[0].minor.yy83 = yylhsminor.yy83;
        break;
      case 59: /* num ::= LP num */
{
    yymsp[-1].minor.yy83=yymsp[0].minor.yy83;
    yymsp[-1].minor.yy83.inclusive = 0;
}
        break;
      case 60: /* num ::= MINUS num */
{
    yymsp[0].minor.yy83.num = -yymsp[0].minor.yy83.num;
    yymsp[-1].minor.yy83 = yymsp[0].minor.yy83;
}
        break;
      case 61: /* term ::= TERM */
      case 62: /* term ::= NUMBER */ yytestcase(yyruleno==62);
{
    yylhsminor.yy0 = yymsp[0].minor.yy0; 
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 63: /* param_term ::= TERM */
      case 68: /* param_any ::= TERM */ yytestcase(yyruleno==68);
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_TERM;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 64: /* param_term ::= NUMBER */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  // Number is treated as a term here
  yylhsminor.yy0.type = QT_TERM;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 65: /* param_term ::= ATTRIBUTE */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_PARAM_TERM;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 66: /* param_any ::= ATTRIBUTE */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_PARAM_ANY;
  yylhsminor.yy0.inclusive = 1;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 67: /* param_any ::= LP ATTRIBUTE */
{
  yymsp[-1].minor.yy0 = yymsp[0].minor.yy0;
  yymsp[-1].minor.yy0.type = QT_PARAM_ANY;
  yymsp[-1].minor.yy0.inclusive = 0; // Could be relevant if type is refined
}
        break;
      case 69: /* param_any ::= num */
{
  yylhsminor.yy0.numval = yymsp[0].minor.yy83.num;
  yylhsminor.yy0.inclusive = yymsp[0].minor.yy83.inclusive;
  yylhsminor.yy0.type = QT_NUMERIC;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  RSQueryParser_ARG_FETCH
  RSQueryParser_CTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  RSQueryParser_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  RSQueryParser_CTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  RSQueryParser_TOKENTYPE yyminor         /* The minor type of the error token */
){
  RSQueryParser_ARG_FETCH
  RSQueryParser_CTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
  
    QueryError_SetErrorFmt(ctx->status, QUERY_ESYNTAX,
        "Syntax error at offset %d near %.*s",
        TOKEN.pos, TOKEN.len, TOKEN.s);
/************ End %syntax_error code ******************************************/
  RSQueryParser_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  RSQueryParser_CTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  RSQueryParser_ARG_FETCH
  RSQueryParser_CTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  RSQueryParser_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  RSQueryParser_CTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "RSQueryParser_Alloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void RSQueryParser_(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  RSQueryParser_TOKENTYPE yyminor       /* The value for the token */
  RSQueryParser_ARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  RSQueryParser_CTX_FETCH
  RSQueryParser_ARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor RSQueryParser_CTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int RSQueryParser_Fallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
