
/* #line 1 "lexer.rl" */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <math.h>

#include "../parse.h"
#include "parser.h"
#include "../../query_node.h"
#include "../../stopwords.h"

/* forward declarations of stuff generated by lemon */

#define RSQuery_Parse_v2 RSQueryParser_v2_ // weird Lemon quirk.. oh well..
#define RSQuery_ParseAlloc_v2 RSQueryParser_v2_Alloc
#define RSQuery_ParseFree_v2 RSQueryParser_v2_Free

void RSQuery_Parse_v2(void *yyp, int yymajor, QueryToken yyminor, QueryParseCtx *ctx);
void *RSQuery_ParseAlloc_v2(void *(*mallocProc)(size_t));
void RSQuery_ParseFree_v2(void *p, void (*freeProc)(void *));


/* #line 307 "lexer.rl" */



/* #line 30 "lexer.c" */
static const char _query_actions[] = {
	0, 1, 0, 1, 1, 1, 2, 1, 
	14, 1, 15, 1, 16, 1, 17, 1, 
	18, 1, 19, 1, 20, 1, 21, 1, 
	22, 1, 23, 1, 24, 1, 25, 1, 
	26, 1, 27, 1, 28, 1, 29, 1, 
	30, 1, 31, 1, 32, 1, 33, 1, 
	34, 1, 35, 1, 36, 1, 37, 1, 
	38, 1, 39, 1, 40, 1, 41, 1, 
	42, 1, 43, 1, 44, 1, 45, 1, 
	46, 1, 47, 2, 2, 3, 2, 2, 
	4, 2, 2, 5, 2, 2, 6, 2, 
	2, 7, 2, 2, 8, 2, 2, 9, 
	2, 2, 10, 2, 2, 11, 2, 2, 
	12, 2, 2, 13
};

static const short _query_key_offsets[] = {
	0, 10, 20, 21, 23, 25, 35, 45, 
	47, 49, 52, 54, 55, 56, 58, 61, 
	63, 73, 113, 124, 134, 145, 147, 148, 
	162, 173, 179, 184, 187, 203, 215, 216, 
	219, 225, 230, 233, 249, 263, 276, 277, 
	287, 300, 310, 322
};

static const char _query_trans_keys[] = {
	9, 13, 32, 47, 58, 64, 91, 96, 
	123, 126, 9, 13, 32, 47, 58, 64, 
	91, 96, 123, 126, 39, 39, 110, 39, 
	102, 9, 13, 32, 47, 58, 64, 91, 
	96, 123, 126, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 48, 57, 48, 
	57, 45, 48, 57, 48, 57, 110, 102, 
	48, 57, 45, 48, 57, 48, 57, 9, 
	13, 32, 47, 58, 64, 91, 96, 123, 
	126, 32, 34, 36, 37, 39, 40, 41, 
	42, 43, 45, 58, 59, 61, 64, 65, 
	91, 92, 93, 95, 97, 105, 123, 124, 
	125, 126, 127, 0, 8, 9, 13, 14, 
	31, 33, 47, 48, 57, 60, 63, 94, 
	96, 42, 92, 96, 0, 47, 58, 64, 
	91, 94, 123, 127, 92, 96, 0, 47, 
	58, 64, 91, 94, 123, 127, 42, 92, 
	96, 0, 47, 58, 64, 91, 94, 123, 
	127, 39, 105, 39, 36, 45, 92, 96, 
	0, 47, 48, 57, 58, 64, 91, 94, 
	123, 127, 42, 92, 96, 0, 47, 58, 
	64, 91, 94, 123, 127, 42, 46, 69, 
	101, 48, 57, 42, 69, 101, 48, 57, 
	42, 48, 57, 42, 46, 69, 92, 96, 
	101, 0, 47, 48, 57, 58, 64, 91, 
	94, 123, 127, 42, 45, 92, 96, 0, 
	47, 58, 64, 91, 94, 123, 127, 105, 
	105, 48, 57, 42, 46, 69, 101, 48, 
	57, 42, 69, 101, 48, 57, 42, 48, 
	57, 42, 46, 69, 92, 96, 101, 0, 
	47, 48, 57, 58, 64, 91, 94, 123, 
	127, 42, 45, 92, 96, 0, 47, 48, 
	57, 58, 64, 91, 94, 123, 127, 42, 
	92, 96, 0, 47, 48, 57, 58, 64, 
	91, 94, 123, 127, 62, 92, 96, 0, 
	47, 58, 64, 91, 94, 123, 127, 42, 
	83, 92, 96, 115, 0, 47, 58, 64, 
	91, 94, 123, 127, 9, 13, 32, 47, 
	58, 64, 91, 96, 123, 126, 42, 92, 
	96, 110, 0, 47, 58, 64, 91, 94, 
	123, 127, 42, 92, 96, 102, 0, 47, 
	58, 64, 91, 94, 123, 127, 0
};

static const char _query_single_lengths[] = {
	0, 0, 1, 2, 2, 0, 2, 0, 
	0, 1, 0, 1, 1, 0, 1, 0, 
	0, 26, 3, 2, 3, 2, 1, 4, 
	3, 4, 3, 1, 6, 4, 1, 1, 
	4, 3, 1, 6, 4, 3, 1, 2, 
	5, 0, 4, 4
};

static const char _query_range_lengths[] = {
	5, 5, 0, 0, 0, 5, 4, 1, 
	1, 1, 1, 0, 0, 1, 1, 1, 
	5, 7, 4, 4, 4, 0, 0, 5, 
	4, 1, 1, 1, 5, 4, 0, 1, 
	1, 1, 1, 5, 5, 5, 0, 4, 
	4, 5, 4, 4
};

static const short _query_index_offsets[] = {
	0, 6, 12, 14, 17, 20, 26, 33, 
	35, 37, 40, 42, 44, 46, 48, 51, 
	53, 59, 93, 101, 108, 116, 119, 121, 
	131, 139, 145, 150, 153, 165, 174, 176, 
	179, 185, 190, 193, 205, 215, 224, 226, 
	233, 243, 249, 258
};

static const char _query_indicies[] = {
	1, 1, 1, 1, 1, 0, 2, 2, 
	2, 2, 2, 0, 4, 3, 4, 6, 
	3, 4, 7, 3, 8, 8, 8, 8, 
	8, 0, 10, 9, 9, 9, 9, 9, 
	8, 11, 9, 13, 12, 14, 15, 12, 
	15, 12, 16, 0, 17, 0, 18, 0, 
	20, 21, 19, 21, 0, 22, 22, 22, 
	22, 22, 0, 24, 26, 27, 28, 29, 
	30, 31, 32, 33, 34, 36, 37, 38, 
	39, 40, 41, 42, 43, 44, 40, 45, 
	46, 47, 48, 49, 23, 23, 24, 23, 
	25, 35, 25, 25, 1, 50, 51, 0, 
	0, 0, 0, 0, 1, 53, 52, 52, 
	52, 52, 52, 2, 50, 53, 54, 54, 
	54, 54, 54, 2, 52, 55, 3, 4, 
	3, 58, 59, 10, 57, 57, 60, 57, 
	57, 57, 8, 62, 10, 61, 61, 61, 
	61, 61, 8, 62, 63, 64, 64, 11, 
	61, 62, 64, 64, 13, 61, 62, 15, 
	61, 62, 63, 65, 10, 61, 65, 61, 
	60, 61, 61, 61, 8, 62, 14, 10, 
	61, 61, 61, 61, 61, 8, 66, 52, 
	66, 68, 67, 50, 70, 71, 71, 68, 
	69, 50, 71, 71, 18, 69, 50, 21, 
	69, 50, 70, 73, 51, 72, 73, 72, 
	35, 72, 72, 72, 1, 50, 20, 51, 
	74, 74, 75, 74, 74, 74, 1, 50, 
	51, 69, 69, 75, 69, 69, 69, 1, 
	76, 52, 77, 0, 0, 0, 0, 0, 
	22, 50, 78, 51, 74, 78, 74, 74, 
	74, 74, 1, 1, 1, 1, 1, 1, 
	52, 50, 51, 74, 79, 74, 74, 74, 
	74, 1, 50, 51, 74, 80, 74, 74, 
	74, 74, 1, 0
};

static const char _query_trans_targs[] = {
	17, 18, 20, 2, 17, 17, 4, 22, 
	24, 17, 5, 25, 17, 26, 10, 27, 
	12, 17, 33, 17, 15, 34, 39, 17, 
	17, 17, 17, 19, 17, 21, 17, 17, 
	23, 30, 31, 35, 17, 17, 38, 39, 
	40, 17, 41, 17, 18, 42, 17, 17, 
	17, 17, 17, 0, 17, 1, 17, 3, 
	17, 17, 6, 7, 28, 17, 17, 8, 
	9, 29, 11, 17, 32, 17, 13, 14, 
	17, 36, 17, 37, 17, 16, 18, 43, 
	18
};

static const char _query_trans_actions[] = {
	73, 102, 84, 0, 45, 69, 0, 90, 
	105, 67, 0, 5, 71, 5, 0, 0, 
	0, 9, 78, 65, 0, 0, 81, 39, 
	35, 37, 11, 99, 29, 99, 15, 17, 
	96, 99, 93, 75, 23, 25, 0, 99, 
	102, 31, 0, 33, 99, 102, 19, 13, 
	21, 27, 41, 0, 59, 0, 51, 0, 
	53, 57, 0, 0, 105, 63, 43, 0, 
	0, 105, 0, 55, 78, 49, 0, 0, 
	47, 102, 61, 78, 7, 0, 87, 102, 
	90
};

static const char _query_to_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 1, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0
};

static const char _query_from_state_actions[] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 3, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0
};

static const short _query_eof_trans[] = {
	1, 1, 1, 6, 6, 1, 10, 10, 
	13, 13, 13, 1, 1, 1, 20, 1, 
	1, 0, 1, 53, 55, 53, 57, 58, 
	62, 62, 62, 62, 62, 62, 53, 68, 
	70, 70, 70, 73, 75, 70, 53, 1, 
	75, 53, 75, 75
};

static const int query_start = 17;
static const int query_first_final = 17;
static const int query_error = -1;

static const int query_en_main = 17;


/* #line 310 "lexer.rl" */

QueryNode *RSQuery_ParseRaw_v2(QueryParseCtx *q) {
  void *pParser = RSQuery_ParseAlloc_v2(rm_malloc);

  
  int cs, act;
  const char* ts = q->raw;
  const char* te = q->raw + q->len;
  
/* #line 238 "lexer.c" */
	{
	cs = query_start;
	ts = 0;
	te = 0;
	act = 0;
	}

/* #line 319 "lexer.rl" */
  QueryToken tok = {.len = 0, .pos = 0, .s = 0};
  
  //parseCtx ctx = {.root = NULL, .ok = 1, .errorMsg = NULL, .q = q};
  const char* p = q->raw;
  const char* pe = q->raw + q->len;
  const char* eof = pe;
  
  
/* #line 255 "lexer.c" */
	{
	int _klen;
	unsigned int _trans;
	const char *_acts;
	unsigned int _nacts;
	const char *_keys;

	if ( p == pe )
		goto _test_eof;
_resume:
	_acts = _query_actions + _query_from_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 1:
/* #line 1 "NONE" */
	{ts = p;}
	break;
/* #line 274 "lexer.c" */
		}
	}

	_keys = _query_trans_keys + _query_key_offsets[cs];
	_trans = _query_index_offsets[cs];

	_klen = _query_single_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + _klen - 1;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + ((_upper-_lower) >> 1);
			if ( (*p) < *_mid )
				_upper = _mid - 1;
			else if ( (*p) > *_mid )
				_lower = _mid + 1;
			else {
				_trans += (unsigned int)(_mid - _keys);
				goto _match;
			}
		}
		_keys += _klen;
		_trans += _klen;
	}

	_klen = _query_range_lengths[cs];
	if ( _klen > 0 ) {
		const char *_lower = _keys;
		const char *_mid;
		const char *_upper = _keys + (_klen<<1) - 2;
		while (1) {
			if ( _upper < _lower )
				break;

			_mid = _lower + (((_upper-_lower) >> 1) & ~1);
			if ( (*p) < _mid[0] )
				_upper = _mid - 2;
			else if ( (*p) > _mid[1] )
				_lower = _mid + 2;
			else {
				_trans += (unsigned int)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += _klen;
	}

_match:
	_trans = _query_indicies[_trans];
_eof_trans:
	cs = _query_trans_targs[_trans];

	if ( _query_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _query_actions + _query_trans_actions[_trans];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 )
	{
		switch ( *_acts++ )
		{
	case 2:
/* #line 1 "NONE" */
	{te = p+1;}
	break;
	case 3:
/* #line 59 "lexer.rl" */
	{act = 1;}
	break;
	case 4:
/* #line 70 "lexer.rl" */
	{act = 2;}
	break;
	case 5:
/* #line 81 "lexer.rl" */
	{act = 3;}
	break;
	case 6:
/* #line 90 "lexer.rl" */
	{act = 4;}
	break;
	case 7:
/* #line 108 "lexer.rl" */
	{act = 6;}
	break;
	case 8:
/* #line 121 "lexer.rl" */
	{act = 7;}
	break;
	case 9:
/* #line 190 "lexer.rl" */
	{act = 16;}
	break;
	case 10:
/* #line 204 "lexer.rl" */
	{act = 18;}
	break;
	case 11:
/* #line 233 "lexer.rl" */
	{act = 23;}
	break;
	case 12:
/* #line 236 "lexer.rl" */
	{act = 25;}
	break;
	case 13:
/* #line 264 "lexer.rl" */
	{act = 27;}
	break;
	case 14:
/* #line 99 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ARROW, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 15:
/* #line 121 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 16:
/* #line 132 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, QUOTE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 17:
/* #line 139 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, OR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 18:
/* #line 146 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 19:
/* #line 154 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RP, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 20:
/* #line 161 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 21:
/* #line 168 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 22:
/* #line 175 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, COLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 23:
/* #line 182 "lexer.rl" */
	{te = p+1;{ 
     tok.pos = ts-q->raw;
     RSQuery_Parse_v2(pParser, SEMICOLON, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
   }}
	break;
	case 24:
/* #line 197 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, TILDE, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 25:
/* #line 211 "lexer.rl" */
	{te = p+1;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, PERCENT, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 26:
/* #line 218 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, LSQB, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }  
  }}
	break;
	case 27:
/* #line 225 "lexer.rl" */
	{te = p+1;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, RSQB, tok, q);   
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    } 
  }}
	break;
	case 28:
/* #line 232 "lexer.rl" */
	{te = p+1;}
	break;
	case 29:
/* #line 233 "lexer.rl" */
	{te = p+1;}
	break;
	case 30:
/* #line 234 "lexer.rl" */
	{te = p+1;}
	break;
	case 31:
/* #line 250 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*ts == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, PREFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 32:
/* #line 278 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, CONTAINS, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 33:
/* #line 292 "lexer.rl" */
	{te = p+1;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 2 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    RSQuery_Parse_v2(pParser, BLOB, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 34:
/* #line 59 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 35:
/* #line 70 "lexer.rl" */
	{te = p;p--;{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 36:
/* #line 90 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 37:
/* #line 121 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 38:
/* #line 190 "lexer.rl" */
	{te = p;p--;{ 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 39:
/* #line 204 "lexer.rl" */
	{te = p;p--;{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 40:
/* #line 233 "lexer.rl" */
	{te = p;p--;}
	break;
	case 41:
/* #line 236 "lexer.rl" */
	{te = p;p--;{
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
      RSQuery_Parse_v2(pParser, TERM, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, STOPWORD, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 42:
/* #line 264 "lexer.rl" */
	{te = p;p--;{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 43:
/* #line 70 "lexer.rl" */
	{{p = ((te))-1;}{ 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 44:
/* #line 204 "lexer.rl" */
	{{p = ((te))-1;}{
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 45:
/* #line 233 "lexer.rl" */
	{{p = ((te))-1;}}
	break;
	case 46:
/* #line 264 "lexer.rl" */
	{{p = ((te))-1;}{
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }}
	break;
	case 47:
/* #line 1 "NONE" */
	{	switch( act ) {
	case 1:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, SIZE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 2:
	{{p = ((te))-1;} 
    tok.s = ts;
    tok.len = te-ts;
    char *ne = (char*)te;
    tok.numval = strtod(tok.s, &ne);
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 3:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, MODIFIER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 4:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - (ts + 1);
    tok.s = ts+1;
    RSQuery_Parse_v2(pParser, ATTRIBUTE, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 6:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    tok.len = te - ts;
    tok.s = ts;
    if (StopWordList_Contains(q->opts->stopwords, "as", 2)) {
      RSQuery_Parse_v2(pParser, AS_S, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, AS_T, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 7:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    tok.s = ts;
    tok.len = te-ts;
    tok.numval = *ts == '-' ? -INFINITY : INFINITY;
    RSQuery_Parse_v2(pParser, NUMBER, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 16:
	{{p = ((te))-1;} 
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, MINUS, tok, q);  
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 18:
	{{p = ((te))-1;}
    tok.pos = ts-q->raw;
    RSQuery_Parse_v2(pParser, STAR, tok, q);
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 25:
	{{p = ((te))-1;}
    tok.len = te-ts;
    tok.s = ts;
    tok.numval = 0;
    tok.pos = ts-q->raw;
    if (!StopWordList_Contains(q->opts->stopwords, tok.s, tok.len)) {
      RSQuery_Parse_v2(pParser, TERM, tok, q);
    } else {
      RSQuery_Parse_v2(pParser, STOPWORD, tok, q);
    }
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	case 27:
	{{p = ((te))-1;}
    int is_attr = (*(ts+1) == '$') ? 1 : 0;
    tok.type = is_attr ? QT_PARAM_TERM : QT_TERM;
    tok.len = te - (ts + 1 + is_attr);
    tok.s = ts + 1 + is_attr;
    tok.numval = 0;
    tok.pos = ts-q->raw;

    RSQuery_Parse_v2(pParser, SUFFIX, tok, q);
    
    if (!QPCTX_ISOK(q)) {
      {p++; goto _out; }
    }
  }
	break;
	default:
	{{p = ((te))-1;}}
	break;
	}
	}
	break;
/* #line 884 "lexer.c" */
		}
	}

_again:
	_acts = _query_actions + _query_to_state_actions[cs];
	_nacts = (unsigned int) *_acts++;
	while ( _nacts-- > 0 ) {
		switch ( *_acts++ ) {
	case 0:
/* #line 1 "NONE" */
	{ts = 0;}
	break;
/* #line 897 "lexer.c" */
		}
	}

	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	if ( p == eof )
	{
	if ( _query_eof_trans[cs] > 0 ) {
		_trans = _query_eof_trans[cs] - 1;
		goto _eof_trans;
	}
	}

	_out: {}
	}

/* #line 327 "lexer.rl" */
  
  if (QPCTX_ISOK(q)) {
    RSQuery_Parse_v2(pParser, 0, tok, q);
  }
  RSQuery_ParseFree_v2(pParser, rm_free);
  if (!QPCTX_ISOK(q) && q->root) {
    QueryNode_Free(q->root);
    q->root = NULL;
  }
  return q->root;
}

