/* This file is automatically generated by Lemon from input grammar
** source file "parser.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <assert.h>

#include "../parse.h"

// unescape a string (non null terminated) and return the new length (may be shorter than the original. This manipulates the string itself
static size_t unescapen(char *s, size_t sz) {

  char *dst = s;
  char *src = dst;
  char *end = s + sz;
  while (src < end) {
      // unescape
      if (*src == '\\' && src + 1 < end &&
         (ispunct(*(src+1)) || isspace(*(src+1)))) {
          ++src;
          continue;
      }
      *dst++ = *src++;
  }

  return (size_t)(dst - s);
}

#define NODENN_BOTH_VALID 0
#define NODENN_BOTH_INVALID -1
#define NODENN_ONE_NULL 1
// Returns:
// 0 if a && b
// -1 if !a && !b
// 1 if a ^ b (i.e. !(a&&b||!a||!b)). The result is stored in `out`
static int one_not_null(void *a, void *b, void *out) {
    if (a && b) {
        return NODENN_BOTH_VALID;
    } else if (a == NULL && b == NULL) {
        return NODENN_BOTH_INVALID;
    } if (a) {
        *(void **)out = a;
        return NODENN_ONE_NULL;
    } else {
        *(void **)out = b;
        return NODENN_ONE_NULL;
    }
}

static void setup_trace(QueryParseCtx *ctx) {
#ifdef PARSER_DEBUG
  void RSQueryParser_Trace(FILE*, char*);
  ctx->trace_log = fopen("/tmp/lemon_query.log", "w");
  RSQueryParser_Trace(ctx->trace_log, "tr: ");
#endif
}

static void reportSyntaxError(QueryError *status, QueryToken* tok, const char *msg) {
  if (tok->type == QT_TERM || tok->type == QT_TERM_CASE) {
    QueryError_SetErrorFmt(status, QUERY_ESYNTAX,
      "%s at offset %d near %.*s", msg, tok->pos, tok->len, tok->s);
  } else if (tok->type == QT_NUMERIC) {
    QueryError_SetErrorFmt(status, QUERY_ESYNTAX,
      "%s at offset %d near %f", msg, tok->pos, tok->numval);
  } else {
    QueryError_SetErrorFmt(status, QUERY_ESYNTAX, "%s at offset %d", msg, tok->pos);
  }
}

/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef LOWEST
#define LOWEST                          1
#define TEXTEXPR                        2
#define ORX                             3
#define OR                              4
#define MODIFIER                        5
#define RP                              6
#define RB                              7
#define RSQB                            8
#define TERM                            9
#define QUOTE                          10
#define LP                             11
#define LB                             12
#define LSQB                           13
#define TILDE                          14
#define MINUS                          15
#define AND                            16
#define ARROW                          17
#define COLON                          18
#define NUMBER                         19
#define SIZE                           20
#define STOPWORD                       21
#define STAR                           22
#define TAGLIST                        23
#define TERMLIST                       24
#define PREFIX                         25
#define PERCENT                        26
#define ATTRIBUTE                      27
#define BLOB                           28
#define AS_S                           29
#define AS_T                           30
#define SEMICOLON                      31
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    RSQueryParser_v2_TOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is RSQueryParser_v2_TOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    RSQueryParser_v2_ARG_SDECL     A static variable declaration for the %extra_argument
**    RSQueryParser_v2_ARG_PDECL     A parameter declaration for the %extra_argument
**    RSQueryParser_v2_ARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    RSQueryParser_v2_ARG_STORE     Code to store %extra_argument into yypParser
**    RSQueryParser_v2_ARG_FETCH     Code to extract %extra_argument from yypParser
**    RSQueryParser_v2_CTX_*         As RSQueryParser_v2_ARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 60
#define YYACTIONTYPE unsigned short int
#define RSQueryParser_v2_TOKENTYPE QueryToken
typedef union {
  int yyinit;
  RSQueryParser_v2_TOKENTYPE yy0;
  SingleVectorQueryParam yy5;
  VectorQueryParams yy26;
  QueryAttribute * yy33;
  QueryAttribute yy55;
  Vector* yy66;
  QueryParam * yy86;
  QueryNode * yy107;
  RangeNumber yy119;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 256
#endif
#define RSQueryParser_v2_ARG_SDECL  QueryParseCtx *ctx ;
#define RSQueryParser_v2_ARG_PDECL , QueryParseCtx *ctx 
#define RSQueryParser_v2_ARG_PARAM ,ctx 
#define RSQueryParser_v2_ARG_FETCH  QueryParseCtx *ctx =yypParser->ctx ;
#define RSQueryParser_v2_ARG_STORE yypParser->ctx =ctx ;
#define RSQueryParser_v2_CTX_SDECL
#define RSQueryParser_v2_CTX_PDECL
#define RSQueryParser_v2_CTX_PARAM
#define RSQueryParser_v2_CTX_FETCH
#define RSQueryParser_v2_CTX_STORE
#define YYFALLBACK 1
#define YYNSTATE             115
#define YYNRULE              99
#define YYNRULE_WITH_ACTION  95
#define YYNTOKEN             32
#define YY_MAX_SHIFT         114
#define YY_MIN_SHIFTREDUCE   181
#define YY_MAX_SHIFTREDUCE   279
#define YY_ERROR_ACTION      280
#define YY_ACCEPT_ACTION     281
#define YY_NO_ACTION         282
#define YY_MIN_REDUCE        283
#define YY_MAX_REDUCE        381
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (699)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   377,  360,   45,  104,   12,  230,  199,   47,  105,  266,
 /*    10 */    44,   15,  352,   58,   13,   14,   57,   92,  318,  267,
 /*    20 */   268,  214,  377,  304,   78,  222,   56,  269,  223,   93,
 /*    30 */    16,  230,  200,   68,  110,  266,   44,   15,  266,  208,
 /*    40 */    13,   14,   63,  112,   72,  267,  268,  214,  267,  268,
 /*    50 */   217,  222,   56,  269,  223,  283,  269,   84,   42,   12,
 /*    60 */   230,  377,  279,  278,  266,   44,   15,  359,   46,   13,
 /*    70 */    14,  111,   77,  206,  267,  268,  214,  263,  351,   58,
 /*    80 */   222,   56,  269,  223,  284,   87,   42,  264,  265,  230,
 /*    90 */   274,  355,   59,  266,   44,    1,   64,   74,   13,   14,
 /*   100 */   260,  259,  207,  267,  268,  214,  276,  363,  272,  222,
 /*   110 */    56,  269,  223,  102,   16,  230,  377,   91,   42,  266,
 /*   120 */    44,   15,   73,   48,   13,   14,   74,   75,  358,  267,
 /*   130 */   268,  214,  304,   82,  364,  222,   56,  269,  223,  230,
 /*   140 */    12,  230,  270,   54,   50,  266,   44,   15,  285,  271,
 /*   150 */    13,   14,  317,   92,   70,  267,  268,  214,   53,   52,
 /*   160 */    71,  222,   56,  269,  223,   88,   16,  230,   30,  303,
 /*   170 */    89,  266,   44,   15,   26,  334,   13,   14,  305,  112,
 /*   180 */   333,  267,  268,  214,  349,   83,  277,  222,   56,  269,
 /*   190 */   223,   86,   34,   43,  200,  350,  233,  266,   44,   33,
 /*   200 */   266,  255,   31,   32,  348,  112,   51,  267,  268,  214,
 /*   210 */   267,  268,   96,  222,   56,  269,  223,   62,  269,  230,
 /*   220 */   266,   90,   53,  266,   44,    1,  245,  227,   13,   14,
 /*   230 */   267,  268,   94,  267,  268,  214,  276,   55,  269,  222,
 /*   240 */    56,  269,  223,  314,  315,  230,  228,  113,   38,  266,
 /*   250 */    44,   15,   95,  229,   13,   14,   97,   92,   98,  267,
 /*   260 */   268,  214,  313,  226,  100,  222,   56,  269,  223,  314,
 /*   270 */   315,  230,  101,  113,   39,  266,   44,   15,  225,  103,
 /*   280 */    13,   14,  224,  112,  367,  267,  268,  214,  313,  366,
 /*   290 */   365,  222,   56,  269,  223,  266,   44,   33,   41,   49,
 /*   300 */    31,   32,  210,  209,  282,  267,  268,  214,   69,   54,
 /*   310 */    34,  222,   56,  269,  223,  266,   44,   33,   35,   17,
 /*   320 */    31,   32,  282,  112,  282,  267,  268,  214,  282,  282,
 /*   330 */   282,  222,   56,  269,  223,  314,  315,  230,  282,  113,
 /*   340 */    36,  266,   44,   15,  282,  282,   13,   14,  282,  282,
 /*   350 */   282,  267,  268,  214,  313,  282,  282,  222,   56,  269,
 /*   360 */   223,  266,   44,   33,  282,  282,   31,   32,  282,  112,
 /*   370 */   282,  267,  268,  214,  282,  282,  282,  222,   56,  269,
 /*   380 */   223,  266,   44,   33,  282,  282,   31,   32,  338,  282,
 /*   390 */    61,  267,  268,  214,  282,   80,  282,  222,   56,  269,
 /*   400 */   223,  266,    4,  282,  282,  314,  315,   67,  114,  113,
 /*   410 */     5,  267,  268,  235,  282,  282,  282,  222,   79,  269,
 /*   420 */   282,  281,   76,   81,  313,    2,  282,  282,  314,  315,
 /*   430 */   282,  114,  113,    3,  314,  315,  282,  282,  113,   40,
 /*   440 */   282,   79,  346,  282,  282,   85,   81,  313,  282,  344,
 /*   450 */   282,   22,  282,  313,  314,  315,  282,  114,  113,   25,
 /*   460 */   282,  282,   23,  282,  282,  314,  315,   79,  114,  113,
 /*   470 */    24,   65,   81,  313,  282,   64,  282,  282,   79,  260,
 /*   480 */   259,  314,  315,   81,  313,  113,   37,    9,  282,  282,
 /*   490 */   314,  315,  282,  114,  113,   10,  282,  282,   19,  282,
 /*   500 */   313,  314,  315,   79,  114,  113,   20,  282,   81,  313,
 /*   510 */   282,  282,  282,  282,   79,  282,  282,  314,  315,   81,
 /*   520 */   313,  113,   27,   18,  282,  282,  314,  315,  282,  114,
 /*   530 */   113,   21,  282,  282,    2,  282,  313,  314,  315,   79,
 /*   540 */   114,  113,    3,  282,   81,  313,  282,  282,  282,  282,
 /*   550 */    79,  282,  282,  314,  315,   81,  313,  113,   29,    8,
 /*   560 */   282,  282,  314,  315,  282,  114,  113,   11,  282,  282,
 /*   570 */     6,  282,  313,  314,  315,   79,  114,  113,    7,  282,
 /*   580 */    81,  313,  282,  282,  282,   92,   79,  267,  268,  214,
 /*   590 */   282,   81,  313,  222,   56,  269,  223,  282,  112,  282,
 /*   600 */   267,  268,  214,  282,  282,  108,  222,   56,  269,  223,
 /*   610 */   282,  267,  268,  214,  282,  107,  106,  222,   56,  269,
 /*   620 */   223,  243,  274,  109,   59,  314,  315,  266,   64,  113,
 /*   630 */    28,  282,  260,  259,  282,  282,  266,  267,  268,  239,
 /*   640 */   272,  282,  282,  222,  313,  269,  267,  268,  254,   65,
 /*   650 */   266,  282,  282,   64,  269,  282,  266,  260,  259,  266,
 /*   660 */   267,  268,  217,  282,  282,  273,  267,  268,  269,  267,
 /*   670 */   268,   99,  282,  282,  269,  282,  282,  269,  282,  342,
 /*   680 */   282,   60,  282,  282,  282,  282,  282,  282,  282,  282,
 /*   690 */   282,  282,  282,  282,  282,  282,  282,  282,   66,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    49,   46,   47,   54,    4,    5,    6,   56,   54,    9,
 /*    10 */    10,   11,   57,   58,   14,   15,   37,   17,   54,   19,
 /*    20 */    20,   21,   49,   33,   34,   25,   26,   27,   28,   56,
 /*    30 */     4,    5,    6,   54,   55,    9,   10,   11,    9,   10,
 /*    40 */    14,   15,    9,   17,    9,   19,   20,   21,   19,   20,
 /*    50 */    21,   25,   26,   27,   28,    0,   27,   44,   45,    4,
 /*    60 */     5,   49,   29,   30,    9,   10,   11,   46,   56,   14,
 /*    70 */    15,   27,   17,    7,   19,   20,   21,    9,   57,   58,
 /*    80 */    25,   26,   27,   28,    0,   44,   45,   19,   20,    5,
 /*    90 */     9,   54,   11,    9,   10,   11,   15,   31,   14,   15,
 /*   100 */    19,   20,    7,   19,   20,   21,   22,   49,   27,   25,
 /*   110 */    26,   27,   28,   54,    4,    5,   49,   44,   45,    9,
 /*   120 */    10,   11,   59,   56,   14,   15,   31,   17,   54,   19,
 /*   130 */    20,   21,   33,   34,   49,   25,   26,   27,   28,    5,
 /*   140 */     4,    5,   20,   12,   13,    9,   10,   11,    0,   27,
 /*   150 */    14,   15,   54,   17,    4,   19,   20,   21,   12,   13,
 /*   160 */     4,   25,   26,   27,   28,   17,    4,    5,   18,   54,
 /*   170 */    53,    9,   10,   11,   18,   55,   14,   15,   33,   17,
 /*   180 */    55,   19,   20,   21,    0,    8,    6,   25,   26,   27,
 /*   190 */    28,    8,    4,    4,    6,    0,    7,    9,   10,   11,
 /*   200 */     9,   27,   14,   15,    0,   17,   13,   19,   20,   21,
 /*   210 */    19,   20,   21,   25,   26,   27,   28,   26,   27,    5,
 /*   220 */     9,    8,   12,    9,   10,   11,    8,   26,   14,   15,
 /*   230 */    19,   20,   21,   19,   20,   21,   22,   26,   27,   25,
 /*   240 */    26,   27,   28,   35,   36,    5,   26,   39,   40,    9,
 /*   250 */    10,   11,   26,   26,   14,   15,   26,   17,   26,   19,
 /*   260 */    20,   21,   54,   26,   26,   25,   26,   27,   28,   35,
 /*   270 */    36,    5,   26,   39,   40,    9,   10,   11,   26,   26,
 /*   280 */    14,   15,   26,   17,   10,   19,   20,   21,   54,   10,
 /*   290 */    10,   25,   26,   27,   28,    9,   10,   11,   12,   13,
 /*   300 */    14,   15,   10,   10,   60,   19,   20,   21,   18,   12,
 /*   310 */     4,   25,   26,   27,   28,    9,   10,   11,    4,    4,
 /*   320 */    14,   15,   60,   17,   60,   19,   20,   21,   60,   60,
 /*   330 */    60,   25,   26,   27,   28,   35,   36,    5,   60,   39,
 /*   340 */    40,    9,   10,   11,   60,   60,   14,   15,   60,   60,
 /*   350 */    60,   19,   20,   21,   54,   60,   60,   25,   26,   27,
 /*   360 */    28,    9,   10,   11,   60,   60,   14,   15,   60,   17,
 /*   370 */    60,   19,   20,   21,   60,   60,   60,   25,   26,   27,
 /*   380 */    28,    9,   10,   11,   60,   60,   14,   15,   35,   60,
 /*   390 */    37,   19,   20,   21,   60,   42,   60,   25,   26,   27,
 /*   400 */    28,    9,   32,   60,   60,   35,   36,   54,   38,   39,
 /*   410 */    40,   19,   20,   21,   60,   60,   60,   25,   48,   27,
 /*   420 */    60,   51,   52,   53,   54,   32,   60,   60,   35,   36,
 /*   430 */    60,   38,   39,   40,   35,   36,   60,   60,   39,   40,
 /*   440 */    60,   48,   43,   60,   60,   52,   53,   54,   60,   50,
 /*   450 */    60,   32,   60,   54,   35,   36,   60,   38,   39,   40,
 /*   460 */    60,   60,   32,   60,   60,   35,   36,   48,   38,   39,
 /*   470 */    40,   11,   53,   54,   60,   15,   60,   60,   48,   19,
 /*   480 */    20,   35,   36,   53,   54,   39,   40,   32,   60,   60,
 /*   490 */    35,   36,   60,   38,   39,   40,   60,   60,   32,   60,
 /*   500 */    54,   35,   36,   48,   38,   39,   40,   60,   53,   54,
 /*   510 */    60,   60,   60,   60,   48,   60,   60,   35,   36,   53,
 /*   520 */    54,   39,   40,   32,   60,   60,   35,   36,   60,   38,
 /*   530 */    39,   40,   60,   60,   32,   60,   54,   35,   36,   48,
 /*   540 */    38,   39,   40,   60,   53,   54,   60,   60,   60,   60,
 /*   550 */    48,   60,   60,   35,   36,   53,   54,   39,   40,   32,
 /*   560 */    60,   60,   35,   36,   60,   38,   39,   40,   60,   60,
 /*   570 */    32,   60,   54,   35,   36,   48,   38,   39,   40,   60,
 /*   580 */    53,   54,   60,   60,   60,   17,   48,   19,   20,   21,
 /*   590 */    60,   53,   54,   25,   26,   27,   28,   60,   17,   60,
 /*   600 */    19,   20,   21,   60,   60,    9,   25,   26,   27,   28,
 /*   610 */    60,   19,   20,   21,   60,   19,   20,   25,   26,   27,
 /*   620 */    28,    8,    9,   27,   11,   35,   36,    9,   15,   39,
 /*   630 */    40,   60,   19,   20,   60,   60,    9,   19,   20,   21,
 /*   640 */    27,   60,   60,   25,   54,   27,   19,   20,   21,   11,
 /*   650 */     9,   60,   60,   15,   27,   60,    9,   19,   20,    9,
 /*   660 */    19,   20,   21,   60,   60,   27,   19,   20,   27,   19,
 /*   670 */    20,   21,   60,   60,   27,   60,   60,   27,   60,   35,
 /*   680 */    60,   37,   60,   60,   60,   60,   60,   60,   60,   60,
 /*   690 */    60,   60,   60,   60,   60,   60,   60,   60,   54,   32,
 /*   700 */    32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
 /*   710 */    32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
 /*   720 */    32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
 /*   730 */    32,
};
#define YY_SHIFT_COUNT    (114)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (650)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    84,  214,    0,   26,   55,  110,  136,  162,  240,  240,
 /*    10 */   266,  266,  332,  332,  332,  332,  332,  332,  568,  568,
 /*    20 */   581,  581,  568,  568,  581,  581,  286,  188,  306,  352,
 /*    30 */   372,  372,  372,  372,  372,  372,  581,  581,  581,  592,
 /*    40 */   592,  392,   33,  618,  596,   33,  613,   81,   81,   81,
 /*    50 */    35,   35,   35,   44,   44,  191,  211,   29,  627,  638,
 /*    60 */   641,  641,  650,  647,  460,  460,  647,  647,  647,  647,
 /*    70 */    68,   68,  122,  134,   44,  131,  148,  146,   66,  150,
 /*    80 */   189,  156,   95,  184,  177,  180,  195,  183,  193,  174,
 /*    90 */   204,  213,  210,  218,  201,  220,  226,  227,  230,  232,
 /*   100 */   237,  238,  246,  252,  253,  256,  274,  279,  280,  292,
 /*   110 */   293,  290,  297,  314,  315,
};
#define YY_REDUCE_COUNT (74)
#define YY_REDUCE_MIN   (-51)
#define YY_REDUCE_MAX   (644)
static const short yy_reduce_ofst[] = {
 /*     0 */   370,  393,  419,  430,  419,  430,  419,  430,  419,  419,
 /*    10 */   430,  430,  455,  466,  491,  502,  527,  538,  419,  419,
 /*    20 */   430,  430,  419,  419,  430,  430,  399,  208,  208,  208,
 /*    30 */   234,  300,  446,  482,  518,  590,  208,  208,  208,  208,
 /*    40 */   208,  353,  -45,  644,  -21,   21,  -49,  -27,   12,   67,
 /*    50 */    13,   41,   73,  -10,   99,  -51,  -46,  -36,   37,   58,
 /*    60 */   -36,  -36,   59,   74,   85,   58,   98,   98,   98,  115,
 /*    70 */   120,  125,   63,  117,  145,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   280,  280,  280,  280,  280,  286,  293,  286,  294,  292,
 /*    10 */   295,  297,  280,  280,  280,  280,  280,  280,  320,  322,
 /*    20 */   323,  321,  287,  288,  290,  289,  280,  280,  298,  297,
 /*    30 */   280,  280,  280,  280,  280,  280,  323,  321,  290,  300,
 /*    40 */   299,  280,  354,  280,  280,  353,  280,  280,  280,  280,
 /*    50 */   280,  280,  280,  307,  307,  280,  280,  280,  280,  280,
 /*    60 */   343,  339,  280,  280,  280,  280,  340,  336,  280,  280,
 /*    70 */   280,  280,  280,  280,  306,  280,  280,  280,  280,  280,
 /*    80 */   280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
 /*    90 */   280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
 /*   100 */   280,  280,  280,  280,  280,  280,  370,  369,  368,  371,
 /*   110 */   280,  280,  280,  296,  291,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
    0,  /*          $ => nothing */
    0,  /*     LOWEST => nothing */
    0,  /*   TEXTEXPR => nothing */
    0,  /*        ORX => nothing */
    0,  /*         OR => nothing */
    0,  /*   MODIFIER => nothing */
    0,  /*         RP => nothing */
    0,  /*         RB => nothing */
    0,  /*       RSQB => nothing */
    0,  /*       TERM => nothing */
    0,  /*      QUOTE => nothing */
    0,  /*         LP => nothing */
    0,  /*         LB => nothing */
    0,  /*       LSQB => nothing */
    0,  /*      TILDE => nothing */
    0,  /*      MINUS => nothing */
    0,  /*        AND => nothing */
    0,  /*      ARROW => nothing */
    0,  /*      COLON => nothing */
    0,  /*     NUMBER => nothing */
    0,  /*       SIZE => nothing */
    0,  /*   STOPWORD => nothing */
    0,  /*       STAR => nothing */
    0,  /*    TAGLIST => nothing */
    0,  /*   TERMLIST => nothing */
    0,  /*     PREFIX => nothing */
    0,  /*    PERCENT => nothing */
    0,  /*  ATTRIBUTE => nothing */
    0,  /*       BLOB => nothing */
   21,  /*       AS_S => STOPWORD */
    9,  /*       AS_T => TERM */
    0,  /*  SEMICOLON => nothing */
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  RSQueryParser_v2_ARG_SDECL                /* A place to hold %extra_argument */
  RSQueryParser_v2_CTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void RSQueryParser_v2_Trace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "LOWEST",
  /*    2 */ "TEXTEXPR",
  /*    3 */ "ORX",
  /*    4 */ "OR",
  /*    5 */ "MODIFIER",
  /*    6 */ "RP",
  /*    7 */ "RB",
  /*    8 */ "RSQB",
  /*    9 */ "TERM",
  /*   10 */ "QUOTE",
  /*   11 */ "LP",
  /*   12 */ "LB",
  /*   13 */ "LSQB",
  /*   14 */ "TILDE",
  /*   15 */ "MINUS",
  /*   16 */ "AND",
  /*   17 */ "ARROW",
  /*   18 */ "COLON",
  /*   19 */ "NUMBER",
  /*   20 */ "SIZE",
  /*   21 */ "STOPWORD",
  /*   22 */ "STAR",
  /*   23 */ "TAGLIST",
  /*   24 */ "TERMLIST",
  /*   25 */ "PREFIX",
  /*   26 */ "PERCENT",
  /*   27 */ "ATTRIBUTE",
  /*   28 */ "BLOB",
  /*   29 */ "AS_S",
  /*   30 */ "AS_T",
  /*   31 */ "SEMICOLON",
  /*   32 */ "expr",
  /*   33 */ "attribute",
  /*   34 */ "attribute_list",
  /*   35 */ "prefix",
  /*   36 */ "blob",
  /*   37 */ "termlist",
  /*   38 */ "union",
  /*   39 */ "text_union",
  /*   40 */ "text_expr",
  /*   41 */ "fuzzy",
  /*   42 */ "tag_list",
  /*   43 */ "geo_filter",
  /*   44 */ "vector_query",
  /*   45 */ "vector_command",
  /*   46 */ "vector_attribute",
  /*   47 */ "vector_attribute_list",
  /*   48 */ "modifierlist",
  /*   49 */ "num",
  /*   50 */ "numeric_range",
  /*   51 */ "query",
  /*   52 */ "star",
  /*   53 */ "modifier",
  /*   54 */ "param_term",
  /*   55 */ "term",
  /*   56 */ "param_any",
  /*   57 */ "vector_score_field",
  /*   58 */ "as",
  /*   59 */ "param_size",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "query ::= expr",
 /*   1 */ "query ::=",
 /*   2 */ "query ::= star",
 /*   3 */ "expr ::= text_expr",
 /*   4 */ "expr ::= expr expr",
 /*   5 */ "expr ::= text_expr expr",
 /*   6 */ "expr ::= expr text_expr",
 /*   7 */ "text_expr ::= text_expr text_expr",
 /*   8 */ "expr ::= union",
 /*   9 */ "union ::= expr OR expr",
 /*  10 */ "union ::= union OR expr",
 /*  11 */ "union ::= text_expr OR expr",
 /*  12 */ "union ::= expr OR text_expr",
 /*  13 */ "text_expr ::= text_union",
 /*  14 */ "text_union ::= text_expr OR text_expr",
 /*  15 */ "text_union ::= text_union OR text_expr",
 /*  16 */ "expr ::= modifier COLON text_expr",
 /*  17 */ "expr ::= modifierlist COLON text_expr",
 /*  18 */ "expr ::= LP expr RP",
 /*  19 */ "text_expr ::= LP text_expr RP",
 /*  20 */ "attribute ::= ATTRIBUTE COLON param_term",
 /*  21 */ "attribute_list ::= attribute",
 /*  22 */ "attribute_list ::= attribute_list SEMICOLON attribute",
 /*  23 */ "attribute_list ::= attribute_list SEMICOLON",
 /*  24 */ "attribute_list ::=",
 /*  25 */ "expr ::= expr ARROW LB attribute_list RB",
 /*  26 */ "text_expr ::= text_expr ARROW LB attribute_list RB",
 /*  27 */ "text_expr ::= QUOTE termlist QUOTE",
 /*  28 */ "text_expr ::= QUOTE term QUOTE",
 /*  29 */ "text_expr ::= QUOTE ATTRIBUTE QUOTE",
 /*  30 */ "text_expr ::= param_term",
 /*  31 */ "text_expr ::= prefix",
 /*  32 */ "text_expr ::= blob",
 /*  33 */ "text_expr ::= STOPWORD",
 /*  34 */ "termlist ::= param_term param_term",
 /*  35 */ "termlist ::= termlist param_term",
 /*  36 */ "termlist ::= termlist STOPWORD",
 /*  37 */ "expr ::= MINUS expr",
 /*  38 */ "text_expr ::= MINUS text_expr",
 /*  39 */ "expr ::= TILDE expr",
 /*  40 */ "text_expr ::= TILDE text_expr",
 /*  41 */ "prefix ::= PREFIX",
 /*  42 */ "blob ::= BLOB",
 /*  43 */ "text_expr ::= PERCENT param_term PERCENT",
 /*  44 */ "text_expr ::= PERCENT PERCENT param_term PERCENT PERCENT",
 /*  45 */ "text_expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT",
 /*  46 */ "text_expr ::= PERCENT STOPWORD PERCENT",
 /*  47 */ "text_expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT",
 /*  48 */ "text_expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT",
 /*  49 */ "modifier ::= MODIFIER",
 /*  50 */ "modifierlist ::= modifier OR term",
 /*  51 */ "modifierlist ::= modifierlist OR term",
 /*  52 */ "expr ::= modifier COLON LB tag_list RB",
 /*  53 */ "tag_list ::= param_term",
 /*  54 */ "tag_list ::= STOPWORD",
 /*  55 */ "tag_list ::= prefix",
 /*  56 */ "tag_list ::= termlist",
 /*  57 */ "tag_list ::= tag_list OR param_term",
 /*  58 */ "tag_list ::= tag_list OR STOPWORD",
 /*  59 */ "tag_list ::= tag_list OR prefix",
 /*  60 */ "tag_list ::= tag_list OR termlist",
 /*  61 */ "expr ::= modifier COLON numeric_range",
 /*  62 */ "numeric_range ::= LSQB param_any param_any RSQB",
 /*  63 */ "expr ::= modifier COLON geo_filter",
 /*  64 */ "geo_filter ::= LSQB param_any param_any param_any param_any RSQB",
 /*  65 */ "query ::= expr ARROW LSQB vector_query RSQB",
 /*  66 */ "query ::= text_expr ARROW LSQB vector_query RSQB",
 /*  67 */ "query ::= star ARROW LSQB vector_query RSQB",
 /*  68 */ "vector_query ::= vector_command vector_attribute_list vector_score_field",
 /*  69 */ "vector_query ::= vector_command vector_score_field",
 /*  70 */ "vector_query ::= vector_command vector_attribute_list",
 /*  71 */ "vector_query ::= vector_command",
 /*  72 */ "vector_score_field ::= as param_term",
 /*  73 */ "vector_score_field ::= as STOPWORD",
 /*  74 */ "vector_command ::= TERM param_size modifier ATTRIBUTE",
 /*  75 */ "vector_attribute ::= TERM param_term",
 /*  76 */ "vector_attribute_list ::= vector_attribute_list vector_attribute",
 /*  77 */ "vector_attribute_list ::= vector_attribute",
 /*  78 */ "num ::= SIZE",
 /*  79 */ "num ::= NUMBER",
 /*  80 */ "num ::= LP num",
 /*  81 */ "num ::= MINUS num",
 /*  82 */ "term ::= TERM",
 /*  83 */ "term ::= NUMBER",
 /*  84 */ "term ::= SIZE",
 /*  85 */ "param_term ::= TERM",
 /*  86 */ "param_term ::= NUMBER",
 /*  87 */ "param_term ::= SIZE",
 /*  88 */ "param_term ::= ATTRIBUTE",
 /*  89 */ "param_size ::= SIZE",
 /*  90 */ "param_size ::= ATTRIBUTE",
 /*  91 */ "param_any ::= ATTRIBUTE",
 /*  92 */ "param_any ::= LP ATTRIBUTE",
 /*  93 */ "param_any ::= TERM",
 /*  94 */ "param_any ::= num",
 /*  95 */ "star ::= STAR",
 /*  96 */ "star ::= LP star RP",
 /*  97 */ "as ::= AS_T",
 /*  98 */ "as ::= AS_S",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to RSQueryParser_v2_Alloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void RSQueryParser_v2_Init(void *yypRawParser RSQueryParser_v2_CTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  RSQueryParser_v2_CTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef RSQueryParser_v2__ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to RSQueryParser_v2_ and RSQueryParser_v2_Free.
*/
void *RSQueryParser_v2_Alloc(void *(*mallocProc)(YYMALLOCARGTYPE) RSQueryParser_v2_CTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    RSQueryParser_v2_CTX_STORE
    RSQueryParser_v2_Init(yypParser RSQueryParser_v2_CTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* RSQueryParser_v2__ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  RSQueryParser_v2_ARG_FETCH
  RSQueryParser_v2_CTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* Default NON-TERMINAL Destructor */
    case 46: /* vector_attribute */
    case 49: /* num */
    case 51: /* query */
    case 52: /* star */
    case 53: /* modifier */
    case 54: /* param_term */
    case 55: /* term */
    case 56: /* param_any */
    case 57: /* vector_score_field */
    case 58: /* as */
    case 59: /* param_size */
{
 
}
      break;
    case 32: /* expr */
    case 35: /* prefix */
    case 36: /* blob */
    case 37: /* termlist */
    case 38: /* union */
    case 39: /* text_union */
    case 40: /* text_expr */
    case 41: /* fuzzy */
    case 42: /* tag_list */
    case 44: /* vector_query */
    case 45: /* vector_command */
{
 QueryNode_Free((yypminor->yy107)); 
}
      break;
    case 33: /* attribute */
{
 rm_free((char*)(yypminor->yy55).value); 
}
      break;
    case 34: /* attribute_list */
{
 array_free_ex((yypminor->yy33), rm_free((char*)((QueryAttribute*)ptr )->value)); 
}
      break;
    case 43: /* geo_filter */
{
 QueryParam_Free((yypminor->yy86)); 
}
      break;
    case 47: /* vector_attribute_list */
{

  array_free((yypminor->yy26).needResolve);
  array_free_ex((yypminor->yy26).params, {
    rm_free((char*)((VecSimRawParam*)ptr)->value);
    rm_free((char*)((VecSimRawParam*)ptr)->name);
  });

}
      break;
    case 48: /* modifierlist */
{

    for (size_t i = 0; i < Vector_Size((yypminor->yy66)); i++) {
        char *s;
        Vector_Get((yypminor->yy66), i, &s);
        rm_free(s);
    }
    Vector_Free((yypminor->yy66));

}
      break;
    case 50: /* numeric_range */
{

  QueryParam_Free((yypminor->yy86));

}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void RSQueryParser_v2_Finalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef RSQueryParser_v2__ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void RSQueryParser_v2_Free(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  RSQueryParser_v2_Finalize(p);
  (*freeProc)(p);
}
#endif /* RSQueryParser_v2__ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int RSQueryParser_v2_StackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int RSQueryParser_v2_Coverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   RSQueryParser_v2_ARG_FETCH
   RSQueryParser_v2_CTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/

  QueryError_SetErrorFmt(ctx->status, QUERY_ESYNTAX,
    "Parser stack overflow. Try moving nested parentheses more to the left");
/******** End %stack_overflow code ********************************************/
   RSQueryParser_v2_ARG_STORE /* Suppress warning about unused %extra_argument var */
   RSQueryParser_v2_CTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  RSQueryParser_v2_TOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    51,  /* (0) query ::= expr */
    51,  /* (1) query ::= */
    51,  /* (2) query ::= star */
    32,  /* (3) expr ::= text_expr */
    32,  /* (4) expr ::= expr expr */
    32,  /* (5) expr ::= text_expr expr */
    32,  /* (6) expr ::= expr text_expr */
    40,  /* (7) text_expr ::= text_expr text_expr */
    32,  /* (8) expr ::= union */
    38,  /* (9) union ::= expr OR expr */
    38,  /* (10) union ::= union OR expr */
    38,  /* (11) union ::= text_expr OR expr */
    38,  /* (12) union ::= expr OR text_expr */
    40,  /* (13) text_expr ::= text_union */
    39,  /* (14) text_union ::= text_expr OR text_expr */
    39,  /* (15) text_union ::= text_union OR text_expr */
    32,  /* (16) expr ::= modifier COLON text_expr */
    32,  /* (17) expr ::= modifierlist COLON text_expr */
    32,  /* (18) expr ::= LP expr RP */
    40,  /* (19) text_expr ::= LP text_expr RP */
    33,  /* (20) attribute ::= ATTRIBUTE COLON param_term */
    34,  /* (21) attribute_list ::= attribute */
    34,  /* (22) attribute_list ::= attribute_list SEMICOLON attribute */
    34,  /* (23) attribute_list ::= attribute_list SEMICOLON */
    34,  /* (24) attribute_list ::= */
    32,  /* (25) expr ::= expr ARROW LB attribute_list RB */
    40,  /* (26) text_expr ::= text_expr ARROW LB attribute_list RB */
    40,  /* (27) text_expr ::= QUOTE termlist QUOTE */
    40,  /* (28) text_expr ::= QUOTE term QUOTE */
    40,  /* (29) text_expr ::= QUOTE ATTRIBUTE QUOTE */
    40,  /* (30) text_expr ::= param_term */
    40,  /* (31) text_expr ::= prefix */
    40,  /* (32) text_expr ::= blob */
    40,  /* (33) text_expr ::= STOPWORD */
    37,  /* (34) termlist ::= param_term param_term */
    37,  /* (35) termlist ::= termlist param_term */
    37,  /* (36) termlist ::= termlist STOPWORD */
    32,  /* (37) expr ::= MINUS expr */
    40,  /* (38) text_expr ::= MINUS text_expr */
    32,  /* (39) expr ::= TILDE expr */
    40,  /* (40) text_expr ::= TILDE text_expr */
    35,  /* (41) prefix ::= PREFIX */
    36,  /* (42) blob ::= BLOB */
    40,  /* (43) text_expr ::= PERCENT param_term PERCENT */
    40,  /* (44) text_expr ::= PERCENT PERCENT param_term PERCENT PERCENT */
    40,  /* (45) text_expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT */
    40,  /* (46) text_expr ::= PERCENT STOPWORD PERCENT */
    40,  /* (47) text_expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT */
    40,  /* (48) text_expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT */
    53,  /* (49) modifier ::= MODIFIER */
    48,  /* (50) modifierlist ::= modifier OR term */
    48,  /* (51) modifierlist ::= modifierlist OR term */
    32,  /* (52) expr ::= modifier COLON LB tag_list RB */
    42,  /* (53) tag_list ::= param_term */
    42,  /* (54) tag_list ::= STOPWORD */
    42,  /* (55) tag_list ::= prefix */
    42,  /* (56) tag_list ::= termlist */
    42,  /* (57) tag_list ::= tag_list OR param_term */
    42,  /* (58) tag_list ::= tag_list OR STOPWORD */
    42,  /* (59) tag_list ::= tag_list OR prefix */
    42,  /* (60) tag_list ::= tag_list OR termlist */
    32,  /* (61) expr ::= modifier COLON numeric_range */
    50,  /* (62) numeric_range ::= LSQB param_any param_any RSQB */
    32,  /* (63) expr ::= modifier COLON geo_filter */
    43,  /* (64) geo_filter ::= LSQB param_any param_any param_any param_any RSQB */
    51,  /* (65) query ::= expr ARROW LSQB vector_query RSQB */
    51,  /* (66) query ::= text_expr ARROW LSQB vector_query RSQB */
    51,  /* (67) query ::= star ARROW LSQB vector_query RSQB */
    44,  /* (68) vector_query ::= vector_command vector_attribute_list vector_score_field */
    44,  /* (69) vector_query ::= vector_command vector_score_field */
    44,  /* (70) vector_query ::= vector_command vector_attribute_list */
    44,  /* (71) vector_query ::= vector_command */
    57,  /* (72) vector_score_field ::= as param_term */
    57,  /* (73) vector_score_field ::= as STOPWORD */
    45,  /* (74) vector_command ::= TERM param_size modifier ATTRIBUTE */
    46,  /* (75) vector_attribute ::= TERM param_term */
    47,  /* (76) vector_attribute_list ::= vector_attribute_list vector_attribute */
    47,  /* (77) vector_attribute_list ::= vector_attribute */
    49,  /* (78) num ::= SIZE */
    49,  /* (79) num ::= NUMBER */
    49,  /* (80) num ::= LP num */
    49,  /* (81) num ::= MINUS num */
    55,  /* (82) term ::= TERM */
    55,  /* (83) term ::= NUMBER */
    55,  /* (84) term ::= SIZE */
    54,  /* (85) param_term ::= TERM */
    54,  /* (86) param_term ::= NUMBER */
    54,  /* (87) param_term ::= SIZE */
    54,  /* (88) param_term ::= ATTRIBUTE */
    59,  /* (89) param_size ::= SIZE */
    59,  /* (90) param_size ::= ATTRIBUTE */
    56,  /* (91) param_any ::= ATTRIBUTE */
    56,  /* (92) param_any ::= LP ATTRIBUTE */
    56,  /* (93) param_any ::= TERM */
    56,  /* (94) param_any ::= num */
    52,  /* (95) star ::= STAR */
    52,  /* (96) star ::= LP star RP */
    58,  /* (97) as ::= AS_T */
    58,  /* (98) as ::= AS_S */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) query ::= expr */
    0,  /* (1) query ::= */
   -1,  /* (2) query ::= star */
   -1,  /* (3) expr ::= text_expr */
   -2,  /* (4) expr ::= expr expr */
   -2,  /* (5) expr ::= text_expr expr */
   -2,  /* (6) expr ::= expr text_expr */
   -2,  /* (7) text_expr ::= text_expr text_expr */
   -1,  /* (8) expr ::= union */
   -3,  /* (9) union ::= expr OR expr */
   -3,  /* (10) union ::= union OR expr */
   -3,  /* (11) union ::= text_expr OR expr */
   -3,  /* (12) union ::= expr OR text_expr */
   -1,  /* (13) text_expr ::= text_union */
   -3,  /* (14) text_union ::= text_expr OR text_expr */
   -3,  /* (15) text_union ::= text_union OR text_expr */
   -3,  /* (16) expr ::= modifier COLON text_expr */
   -3,  /* (17) expr ::= modifierlist COLON text_expr */
   -3,  /* (18) expr ::= LP expr RP */
   -3,  /* (19) text_expr ::= LP text_expr RP */
   -3,  /* (20) attribute ::= ATTRIBUTE COLON param_term */
   -1,  /* (21) attribute_list ::= attribute */
   -3,  /* (22) attribute_list ::= attribute_list SEMICOLON attribute */
   -2,  /* (23) attribute_list ::= attribute_list SEMICOLON */
    0,  /* (24) attribute_list ::= */
   -5,  /* (25) expr ::= expr ARROW LB attribute_list RB */
   -5,  /* (26) text_expr ::= text_expr ARROW LB attribute_list RB */
   -3,  /* (27) text_expr ::= QUOTE termlist QUOTE */
   -3,  /* (28) text_expr ::= QUOTE term QUOTE */
   -3,  /* (29) text_expr ::= QUOTE ATTRIBUTE QUOTE */
   -1,  /* (30) text_expr ::= param_term */
   -1,  /* (31) text_expr ::= prefix */
   -1,  /* (32) text_expr ::= blob */
   -1,  /* (33) text_expr ::= STOPWORD */
   -2,  /* (34) termlist ::= param_term param_term */
   -2,  /* (35) termlist ::= termlist param_term */
   -2,  /* (36) termlist ::= termlist STOPWORD */
   -2,  /* (37) expr ::= MINUS expr */
   -2,  /* (38) text_expr ::= MINUS text_expr */
   -2,  /* (39) expr ::= TILDE expr */
   -2,  /* (40) text_expr ::= TILDE text_expr */
   -1,  /* (41) prefix ::= PREFIX */
   -1,  /* (42) blob ::= BLOB */
   -3,  /* (43) text_expr ::= PERCENT param_term PERCENT */
   -5,  /* (44) text_expr ::= PERCENT PERCENT param_term PERCENT PERCENT */
   -7,  /* (45) text_expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT */
   -3,  /* (46) text_expr ::= PERCENT STOPWORD PERCENT */
   -5,  /* (47) text_expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT */
   -7,  /* (48) text_expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT */
   -1,  /* (49) modifier ::= MODIFIER */
   -3,  /* (50) modifierlist ::= modifier OR term */
   -3,  /* (51) modifierlist ::= modifierlist OR term */
   -5,  /* (52) expr ::= modifier COLON LB tag_list RB */
   -1,  /* (53) tag_list ::= param_term */
   -1,  /* (54) tag_list ::= STOPWORD */
   -1,  /* (55) tag_list ::= prefix */
   -1,  /* (56) tag_list ::= termlist */
   -3,  /* (57) tag_list ::= tag_list OR param_term */
   -3,  /* (58) tag_list ::= tag_list OR STOPWORD */
   -3,  /* (59) tag_list ::= tag_list OR prefix */
   -3,  /* (60) tag_list ::= tag_list OR termlist */
   -3,  /* (61) expr ::= modifier COLON numeric_range */
   -4,  /* (62) numeric_range ::= LSQB param_any param_any RSQB */
   -3,  /* (63) expr ::= modifier COLON geo_filter */
   -6,  /* (64) geo_filter ::= LSQB param_any param_any param_any param_any RSQB */
   -5,  /* (65) query ::= expr ARROW LSQB vector_query RSQB */
   -5,  /* (66) query ::= text_expr ARROW LSQB vector_query RSQB */
   -5,  /* (67) query ::= star ARROW LSQB vector_query RSQB */
   -3,  /* (68) vector_query ::= vector_command vector_attribute_list vector_score_field */
   -2,  /* (69) vector_query ::= vector_command vector_score_field */
   -2,  /* (70) vector_query ::= vector_command vector_attribute_list */
   -1,  /* (71) vector_query ::= vector_command */
   -2,  /* (72) vector_score_field ::= as param_term */
   -2,  /* (73) vector_score_field ::= as STOPWORD */
   -4,  /* (74) vector_command ::= TERM param_size modifier ATTRIBUTE */
   -2,  /* (75) vector_attribute ::= TERM param_term */
   -2,  /* (76) vector_attribute_list ::= vector_attribute_list vector_attribute */
   -1,  /* (77) vector_attribute_list ::= vector_attribute */
   -1,  /* (78) num ::= SIZE */
   -1,  /* (79) num ::= NUMBER */
   -2,  /* (80) num ::= LP num */
   -2,  /* (81) num ::= MINUS num */
   -1,  /* (82) term ::= TERM */
   -1,  /* (83) term ::= NUMBER */
   -1,  /* (84) term ::= SIZE */
   -1,  /* (85) param_term ::= TERM */
   -1,  /* (86) param_term ::= NUMBER */
   -1,  /* (87) param_term ::= SIZE */
   -1,  /* (88) param_term ::= ATTRIBUTE */
   -1,  /* (89) param_size ::= SIZE */
   -1,  /* (90) param_size ::= ATTRIBUTE */
   -1,  /* (91) param_any ::= ATTRIBUTE */
   -2,  /* (92) param_any ::= LP ATTRIBUTE */
   -1,  /* (93) param_any ::= TERM */
   -1,  /* (94) param_any ::= num */
   -1,  /* (95) star ::= STAR */
   -3,  /* (96) star ::= LP star RP */
   -1,  /* (97) as ::= AS_T */
   -1,  /* (98) as ::= AS_S */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  RSQueryParser_v2_TOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  RSQueryParser_v2_CTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  RSQueryParser_v2_ARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* query ::= expr */
{
  setup_trace(ctx);
  ctx->root = yymsp[0].minor.yy107;
}
        break;
      case 1: /* query ::= */
{
  ctx->root = NULL;
}
        break;
      case 2: /* query ::= star */
{  yy_destructor(yypParser,52,&yymsp[0].minor);
{
  setup_trace(ctx);
  ctx->root = NewWildcardNode();
}
}
        break;
      case 3: /* expr ::= text_expr */
      case 8: /* expr ::= union */ yytestcase(yyruleno==8);
      case 13: /* text_expr ::= text_union */ yytestcase(yyruleno==13);
      case 71: /* vector_query ::= vector_command */ yytestcase(yyruleno==71);
{
  yylhsminor.yy107 = yymsp[0].minor.yy107;
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 4: /* expr ::= expr expr */
      case 5: /* expr ::= text_expr expr */ yytestcase(yyruleno==5);
      case 6: /* expr ::= expr text_expr */ yytestcase(yyruleno==6);
      case 7: /* text_expr ::= text_expr text_expr */ yytestcase(yyruleno==7);
{
    int rv = one_not_null(yymsp[-1].minor.yy107, yymsp[0].minor.yy107, (void**)&yylhsminor.yy107);
    if (rv == NODENN_BOTH_INVALID) {
        yylhsminor.yy107 = NULL;
    } else if (rv == NODENN_ONE_NULL) {
        // Nothing- `out` is already assigned
    } else {
        if (yymsp[-1].minor.yy107 && yymsp[-1].minor.yy107->type == QN_PHRASE && yymsp[-1].minor.yy107->pn.exact == 0 &&
            yymsp[-1].minor.yy107->opts.fieldMask == RS_FIELDMASK_ALL ) {
            yylhsminor.yy107 = yymsp[-1].minor.yy107;
        } else {
            yylhsminor.yy107 = NewPhraseNode(0);
            QueryNode_AddChild(yylhsminor.yy107, yymsp[-1].minor.yy107);
        }
        QueryNode_AddChild(yylhsminor.yy107, yymsp[0].minor.yy107);
    }
}
  yymsp[-1].minor.yy107 = yylhsminor.yy107;
        break;
      case 9: /* union ::= expr OR expr */
      case 11: /* union ::= text_expr OR expr */ yytestcase(yyruleno==11);
      case 12: /* union ::= expr OR text_expr */ yytestcase(yyruleno==12);
      case 14: /* text_union ::= text_expr OR text_expr */ yytestcase(yyruleno==14);
{
    int rv = one_not_null(yymsp[-2].minor.yy107, yymsp[0].minor.yy107, (void**)&yylhsminor.yy107);
    if (rv == NODENN_BOTH_INVALID) {
        yylhsminor.yy107 = NULL;
    } else if (rv == NODENN_ONE_NULL) {
        // Nothing- already assigned
    } else {
        if (yymsp[-2].minor.yy107->type == QN_UNION && yymsp[-2].minor.yy107->opts.fieldMask == RS_FIELDMASK_ALL) {
            yylhsminor.yy107 = yymsp[-2].minor.yy107;
        } else {
            yylhsminor.yy107 = NewUnionNode();
            QueryNode_AddChild(yylhsminor.yy107, yymsp[-2].minor.yy107);
            yylhsminor.yy107->opts.fieldMask |= yymsp[-2].minor.yy107->opts.fieldMask;
        }
        // Handle yymsp[0].minor.yy107
        QueryNode_AddChild(yylhsminor.yy107, yymsp[0].minor.yy107);
        yylhsminor.yy107->opts.fieldMask |= yymsp[0].minor.yy107->opts.fieldMask;
        QueryNode_SetFieldMask(yylhsminor.yy107, yylhsminor.yy107->opts.fieldMask);
    }
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 10: /* union ::= union OR expr */
      case 15: /* text_union ::= text_union OR text_expr */ yytestcase(yyruleno==15);
{
    yylhsminor.yy107 = yymsp[-2].minor.yy107;
    if (yymsp[0].minor.yy107) {
        QueryNode_AddChild(yylhsminor.yy107, yymsp[0].minor.yy107);
        yylhsminor.yy107->opts.fieldMask |= yymsp[0].minor.yy107->opts.fieldMask;
        QueryNode_SetFieldMask(yymsp[0].minor.yy107, yylhsminor.yy107->opts.fieldMask);
    }
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 16: /* expr ::= modifier COLON text_expr */
{
    if (yymsp[0].minor.yy107 == NULL) {
        yylhsminor.yy107 = NULL;
    } else {
        if (ctx->sctx->spec) {
            QueryNode_SetFieldMask(yymsp[0].minor.yy107, IndexSpec_GetFieldBit(ctx->sctx->spec, yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len));
        }
        yylhsminor.yy107 = yymsp[0].minor.yy107;
    }
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 17: /* expr ::= modifierlist COLON text_expr */
{

    if (yymsp[0].minor.yy107 == NULL) {
        for (size_t i = 0; i < Vector_Size(yymsp[-2].minor.yy66); i++) {
          char *s;
          Vector_Get(yymsp[-2].minor.yy66, i, &s);
          rm_free(s);
        }
        Vector_Free(yymsp[-2].minor.yy66);
        yylhsminor.yy107 = NULL;
    } else {
        //yymsp[0].minor.yy107->opts.fieldMask = 0;
        t_fieldMask mask = 0;
        for (int i = 0; i < Vector_Size(yymsp[-2].minor.yy66); i++) {
            char *p;
            Vector_Get(yymsp[-2].minor.yy66, i, &p);
            if (ctx->sctx->spec) {
              mask |= IndexSpec_GetFieldBit(ctx->sctx->spec, p, strlen(p));
            }
            rm_free(p);
        }
        Vector_Free(yymsp[-2].minor.yy66);
        QueryNode_SetFieldMask(yymsp[0].minor.yy107, mask);
        yylhsminor.yy107=yymsp[0].minor.yy107;
    }
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 18: /* expr ::= LP expr RP */
      case 19: /* text_expr ::= LP text_expr RP */ yytestcase(yyruleno==19);
{
  yymsp[-2].minor.yy107 = yymsp[-1].minor.yy107;
}
        break;
      case 20: /* attribute ::= ATTRIBUTE COLON param_term */
{
  const char *value = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
  size_t value_len = yymsp[0].minor.yy0.len;
  if (yymsp[0].minor.yy0.type == QT_PARAM_TERM) {
    size_t found_value_len;
    const char *found_value = Param_DictGet(ctx->opts->params, value, &found_value_len, ctx->status);
    if (found_value) {
      rm_free((char*)value);
      value = rm_strndup(found_value, found_value_len);
      value_len = found_value_len;
    }
  }
  yylhsminor.yy55 = (QueryAttribute){ .name = yymsp[-2].minor.yy0.s, .namelen = yymsp[-2].minor.yy0.len, .value = value, .vallen = value_len };
}
  yymsp[-2].minor.yy55 = yylhsminor.yy55;
        break;
      case 21: /* attribute_list ::= attribute */
{
  yylhsminor.yy33 = array_new(QueryAttribute, 2);
  yylhsminor.yy33 = array_append(yylhsminor.yy33, yymsp[0].minor.yy55);
}
  yymsp[0].minor.yy33 = yylhsminor.yy33;
        break;
      case 22: /* attribute_list ::= attribute_list SEMICOLON attribute */
{
  yylhsminor.yy33 = array_append(yymsp[-2].minor.yy33, yymsp[0].minor.yy55);
}
  yymsp[-2].minor.yy33 = yylhsminor.yy33;
        break;
      case 23: /* attribute_list ::= attribute_list SEMICOLON */
{
  yylhsminor.yy33 = yymsp[-1].minor.yy33;
}
  yymsp[-1].minor.yy33 = yylhsminor.yy33;
        break;
      case 24: /* attribute_list ::= */
{
  yymsp[1].minor.yy33 = NULL;
}
        break;
      case 25: /* expr ::= expr ARROW LB attribute_list RB */
      case 26: /* text_expr ::= text_expr ARROW LB attribute_list RB */ yytestcase(yyruleno==26);
{

    if (yymsp[-4].minor.yy107 && yymsp[-1].minor.yy33) {
        QueryNode_ApplyAttributes(yymsp[-4].minor.yy107, yymsp[-1].minor.yy33, array_len(yymsp[-1].minor.yy33), ctx->status);
    }
    array_free_ex(yymsp[-1].minor.yy33, rm_free((char*)((QueryAttribute*)ptr )->value));
    yylhsminor.yy107 = yymsp[-4].minor.yy107;
}
  yymsp[-4].minor.yy107 = yylhsminor.yy107;
        break;
      case 27: /* text_expr ::= QUOTE termlist QUOTE */
{
  // TODO: Quoted/verbatim string in termlist should not be handled as parameters
  // Also need to add the leading '$' which was consumed by the lexer
  yymsp[-1].minor.yy107->pn.exact = 1;
  yymsp[-1].minor.yy107->opts.flags |= QueryNode_Verbatim;

  yymsp[-2].minor.yy107 = yymsp[-1].minor.yy107;
}
        break;
      case 28: /* text_expr ::= QUOTE term QUOTE */
{
  yymsp[-2].minor.yy107 = NewTokenNode(ctx, rm_strdupcase(yymsp[-1].minor.yy0.s, yymsp[-1].minor.yy0.len), -1);
  yymsp[-2].minor.yy107->opts.flags |= QueryNode_Verbatim;
}
        break;
      case 29: /* text_expr ::= QUOTE ATTRIBUTE QUOTE */
{
  // Quoted/verbatim string should not be handled as parameters
  // Also need to add the leading '$' which was consumed by the lexer
  char *s = rm_malloc(yymsp[-1].minor.yy0.len + 1);
  *s = '$';
  memcpy(s + 1, yymsp[-1].minor.yy0.s, yymsp[-1].minor.yy0.len);
  yymsp[-2].minor.yy107 = NewTokenNode(ctx, rm_strdupcase(s, yymsp[-1].minor.yy0.len + 1), -1);
  rm_free(s);
  yymsp[-2].minor.yy107->opts.flags |= QueryNode_Verbatim;
}
        break;
      case 30: /* text_expr ::= param_term */
{
  yylhsminor.yy107 = NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0);
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 31: /* text_expr ::= prefix */
      case 32: /* text_expr ::= blob */ yytestcase(yyruleno==32);
{
yylhsminor.yy107 = yymsp[0].minor.yy107;
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 33: /* text_expr ::= STOPWORD */
{
  yymsp[0].minor.yy107 = NULL;
}
        break;
      case 34: /* termlist ::= param_term param_term */
{
  yylhsminor.yy107 = NewPhraseNode(0);
  QueryNode_AddChild(yylhsminor.yy107, NewTokenNode_WithParams(ctx, &yymsp[-1].minor.yy0));
  QueryNode_AddChild(yylhsminor.yy107, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
}
  yymsp[-1].minor.yy107 = yylhsminor.yy107;
        break;
      case 35: /* termlist ::= termlist param_term */
{
  yylhsminor.yy107 = yymsp[-1].minor.yy107;
  QueryNode_AddChild(yylhsminor.yy107, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
}
  yymsp[-1].minor.yy107 = yylhsminor.yy107;
        break;
      case 36: /* termlist ::= termlist STOPWORD */
{
  yylhsminor.yy107 = yymsp[-1].minor.yy107;
}
  yymsp[-1].minor.yy107 = yylhsminor.yy107;
        break;
      case 37: /* expr ::= MINUS expr */
      case 38: /* text_expr ::= MINUS text_expr */ yytestcase(yyruleno==38);
{
    if (yymsp[0].minor.yy107) {
        yymsp[-1].minor.yy107 = NewNotNode(yymsp[0].minor.yy107);
    } else {
        yymsp[-1].minor.yy107 = NULL;
    }
}
        break;
      case 39: /* expr ::= TILDE expr */
      case 40: /* text_expr ::= TILDE text_expr */ yytestcase(yyruleno==40);
{
    if (yymsp[0].minor.yy107) {
        yymsp[-1].minor.yy107 = NewOptionalNode(yymsp[0].minor.yy107);
    } else {
        yymsp[-1].minor.yy107 = NULL;
    }
}
        break;
      case 41: /* prefix ::= PREFIX */
      case 42: /* blob ::= BLOB */ yytestcase(yyruleno==42);
{
    yylhsminor.yy107 = NewPrefixNode_WithParams(ctx, &yymsp[0].minor.yy0);
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 43: /* text_expr ::= PERCENT param_term PERCENT */
      case 46: /* text_expr ::= PERCENT STOPWORD PERCENT */ yytestcase(yyruleno==46);
{
  yymsp[-2].minor.yy107 = NewFuzzyNode_WithParams(ctx, &yymsp[-1].minor.yy0, 1);
}
        break;
      case 44: /* text_expr ::= PERCENT PERCENT param_term PERCENT PERCENT */
      case 47: /* text_expr ::= PERCENT PERCENT STOPWORD PERCENT PERCENT */ yytestcase(yyruleno==47);
{
  yymsp[-4].minor.yy107 = NewFuzzyNode_WithParams(ctx, &yymsp[-2].minor.yy0, 2);
}
        break;
      case 45: /* text_expr ::= PERCENT PERCENT PERCENT param_term PERCENT PERCENT PERCENT */
      case 48: /* text_expr ::= PERCENT PERCENT PERCENT STOPWORD PERCENT PERCENT PERCENT */ yytestcase(yyruleno==48);
{
  yymsp[-6].minor.yy107 = NewFuzzyNode_WithParams(ctx, &yymsp[-3].minor.yy0, 3);
}
        break;
      case 49: /* modifier ::= MODIFIER */
{
    yymsp[0].minor.yy0.len = unescapen((char*)yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
    yylhsminor.yy0 = yymsp[0].minor.yy0;
 }
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 50: /* modifierlist ::= modifier OR term */
{
    yylhsminor.yy66 = NewVector(char *, 2);
    char *s = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
    Vector_Push(yylhsminor.yy66, s);
    s = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
    Vector_Push(yylhsminor.yy66, s);
}
  yymsp[-2].minor.yy66 = yylhsminor.yy66;
        break;
      case 51: /* modifierlist ::= modifierlist OR term */
{
    char *s = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
    Vector_Push(yymsp[-2].minor.yy66, s);
    yylhsminor.yy66 = yymsp[-2].minor.yy66;
}
  yymsp[-2].minor.yy66 = yylhsminor.yy66;
        break;
      case 52: /* expr ::= modifier COLON LB tag_list RB */
{
    if (!yymsp[-1].minor.yy107) {
        yylhsminor.yy107 = NULL;
    } else {
      // Tag field names must be case sensitive, we can't do rm_strdupcase
        char *s = rm_strndup(yymsp[-4].minor.yy0.s, yymsp[-4].minor.yy0.len);
        size_t slen = unescapen((char*)s, yymsp[-4].minor.yy0.len);

        yylhsminor.yy107 = NewTagNode(s, slen);
        QueryNode_AddChildren(yylhsminor.yy107, yymsp[-1].minor.yy107->children, QueryNode_NumChildren(yymsp[-1].minor.yy107));

        // Set the children count on yymsp[-1].minor.yy107 to 0 so they won't get recursively free'd
        QueryNode_ClearChildren(yymsp[-1].minor.yy107, 0);
        QueryNode_Free(yymsp[-1].minor.yy107);
    }
}
  yymsp[-4].minor.yy107 = yylhsminor.yy107;
        break;
      case 53: /* tag_list ::= param_term */
{
  yylhsminor.yy107 = NewPhraseNode(0);
  if (yymsp[0].minor.yy0.type == QT_TERM)
    yymsp[0].minor.yy0.type = QT_TERM_CASE;
  else if (yymsp[0].minor.yy0.type == QT_PARAM_TERM)
    yymsp[0].minor.yy0.type = QT_PARAM_TERM_CASE;
  QueryNode_AddChild(yylhsminor.yy107, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 54: /* tag_list ::= STOPWORD */
{
    yylhsminor.yy107 = NewPhraseNode(0);
    QueryNode_AddChild(yylhsminor.yy107, NewTokenNode(ctx, rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len), -1));
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 55: /* tag_list ::= prefix */
      case 56: /* tag_list ::= termlist */ yytestcase(yyruleno==56);
{
    yylhsminor.yy107 = NewPhraseNode(0);
    QueryNode_AddChild(yylhsminor.yy107, yymsp[0].minor.yy107);
}
  yymsp[0].minor.yy107 = yylhsminor.yy107;
        break;
      case 57: /* tag_list ::= tag_list OR param_term */
{
  if (yymsp[0].minor.yy0.type == QT_TERM)
    yymsp[0].minor.yy0.type = QT_TERM_CASE;
  else if (yymsp[0].minor.yy0.type == QT_PARAM_TERM)
    yymsp[0].minor.yy0.type = QT_PARAM_TERM_CASE;
  QueryNode_AddChild(yymsp[-2].minor.yy107, NewTokenNode_WithParams(ctx, &yymsp[0].minor.yy0));
  yylhsminor.yy107 = yymsp[-2].minor.yy107;
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 58: /* tag_list ::= tag_list OR STOPWORD */
{
    QueryNode_AddChild(yymsp[-2].minor.yy107, NewTokenNode(ctx, rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len), -1));
    yylhsminor.yy107 = yymsp[-2].minor.yy107;
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 59: /* tag_list ::= tag_list OR prefix */
      case 60: /* tag_list ::= tag_list OR termlist */ yytestcase(yyruleno==60);
{
    QueryNode_AddChild(yymsp[-2].minor.yy107, yymsp[0].minor.yy107);
    yylhsminor.yy107 = yymsp[-2].minor.yy107;
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 61: /* expr ::= modifier COLON numeric_range */
{
  if (yymsp[0].minor.yy86) {
    // we keep the capitalization as is
    yymsp[0].minor.yy86->nf->fieldName = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
    yylhsminor.yy107 = NewNumericNode(yymsp[0].minor.yy86);
  } else {
    yylhsminor.yy107 = NewQueryNode(QN_NULL);
  }
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 62: /* numeric_range ::= LSQB param_any param_any RSQB */
{
  // Update token type to be more specific if possible
  // and detect syntax errors
  QueryToken *badToken = NULL;
  if (yymsp[-2].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-2].minor.yy0.type = QT_PARAM_NUMERIC_MIN_RANGE;
  else if (yymsp[-2].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-2].minor.yy0;
  if (yymsp[-1].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-1].minor.yy0.type = QT_PARAM_NUMERIC_MAX_RANGE;
  else if (!badToken && yymsp[-1].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-1].minor.yy0;

  if (!badToken) {
    yymsp[-3].minor.yy86 = NewNumericFilterQueryParam_WithParams(ctx, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0, yymsp[-2].minor.yy0.inclusive, yymsp[-1].minor.yy0.inclusive);
  } else {
    reportSyntaxError(ctx->status, badToken, "Expecting numeric or parameter");
    yymsp[-3].minor.yy86 = NULL;
  }
}
        break;
      case 63: /* expr ::= modifier COLON geo_filter */
{
  if (yymsp[0].minor.yy86) {
    // we keep the capitalization as is
    yymsp[0].minor.yy86->gf->property = rm_strndup(yymsp[-2].minor.yy0.s, yymsp[-2].minor.yy0.len);
    yylhsminor.yy107 = NewGeofilterNode(yymsp[0].minor.yy86);
  } else {
    yylhsminor.yy107 = NewQueryNode(QN_NULL);
  }
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 64: /* geo_filter ::= LSQB param_any param_any param_any param_any RSQB */
{
  // Update token type to be more specific if possible
  // and detect syntax errors
  QueryToken *badToken = NULL;

  if (yymsp[-4].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-4].minor.yy0.type = QT_PARAM_GEO_COORD;
  else if (yymsp[-4].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-4].minor.yy0;
  if (yymsp[-3].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-3].minor.yy0.type = QT_PARAM_GEO_COORD;
  else if (!badToken && yymsp[-3].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-3].minor.yy0;
  if (yymsp[-2].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-2].minor.yy0.type = QT_PARAM_NUMERIC;
  else if (!badToken && yymsp[-2].minor.yy0.type != QT_NUMERIC)
    badToken = &yymsp[-2].minor.yy0;
  if (yymsp[-1].minor.yy0.type == QT_PARAM_ANY)
    yymsp[-1].minor.yy0.type = QT_PARAM_GEO_UNIT;
  else if (!badToken && yymsp[-1].minor.yy0.type != QT_TERM)
    badToken = &yymsp[-1].minor.yy0;

  if (!badToken) {
    yymsp[-5].minor.yy86 = NewGeoFilterQueryParam_WithParams(ctx, &yymsp[-4].minor.yy0, &yymsp[-3].minor.yy0, &yymsp[-2].minor.yy0, &yymsp[-1].minor.yy0);
  } else {
    reportSyntaxError(ctx->status, badToken, "Syntax error");
    yymsp[-5].minor.yy86 = NULL;
  }
}
        break;
      case 65: /* query ::= expr ARROW LSQB vector_query RSQB */
      case 66: /* query ::= text_expr ARROW LSQB vector_query RSQB */ yytestcase(yyruleno==66);
{ // main parse, hybrid query as entire query case.
  setup_trace(ctx);
  switch (yymsp[-1].minor.yy107->vn.vq->type) {
    case VECSIM_QT_KNN:
      yymsp[-1].minor.yy107->vn.vq->knn.order = BY_SCORE;
      break;
  }
  ctx->root = yymsp[-1].minor.yy107;
  if (yymsp[-4].minor.yy107) {
    QueryNode_AddChild(yymsp[-1].minor.yy107, yymsp[-4].minor.yy107);
  }
}
        break;
      case 67: /* query ::= star ARROW LSQB vector_query RSQB */
{  yy_destructor(yypParser,52,&yymsp[-4].minor);
{ // main parse, simple vecsim search as entire query case.
  setup_trace(ctx);
  switch (yymsp[-1].minor.yy107->vn.vq->type) {
    case VECSIM_QT_KNN:
      yymsp[-1].minor.yy107->vn.vq->knn.order = BY_SCORE;
      break;
  }
  ctx->root = yymsp[-1].minor.yy107;
}
}
        break;
      case 68: /* vector_query ::= vector_command vector_attribute_list vector_score_field */
{
  if (yymsp[-2].minor.yy107->vn.vq->scoreField) {
    rm_free(yymsp[-2].minor.yy107->vn.vq->scoreField);
    yymsp[-2].minor.yy107->vn.vq->scoreField = NULL;
  }
  yymsp[-2].minor.yy107->params = array_grow(yymsp[-2].minor.yy107->params, 1);
  memset(&array_tail(yymsp[-2].minor.yy107->params), 0, sizeof(*yymsp[-2].minor.yy107->params));
  QueryNode_SetParam(ctx, &(array_tail(yymsp[-2].minor.yy107->params)), &(yymsp[-2].minor.yy107->vn.vq->scoreField), NULL, &yymsp[0].minor.yy0);
  yymsp[-2].minor.yy107->vn.vq->params = yymsp[-1].minor.yy26;
  yylhsminor.yy107 = yymsp[-2].minor.yy107;
}
  yymsp[-2].minor.yy107 = yylhsminor.yy107;
        break;
      case 69: /* vector_query ::= vector_command vector_score_field */
{
  if (yymsp[-1].minor.yy107->vn.vq->scoreField) {
    rm_free(yymsp[-1].minor.yy107->vn.vq->scoreField);
    yymsp[-1].minor.yy107->vn.vq->scoreField = NULL;
  }
  yymsp[-1].minor.yy107->params = array_grow(yymsp[-1].minor.yy107->params, 1);
  memset(&array_tail(yymsp[-1].minor.yy107->params), 0, sizeof(*yymsp[-1].minor.yy107->params));
  QueryNode_SetParam(ctx, &(array_tail(yymsp[-1].minor.yy107->params)), &(yymsp[-1].minor.yy107->vn.vq->scoreField), NULL, &yymsp[0].minor.yy0);
  yylhsminor.yy107 = yymsp[-1].minor.yy107;
}
  yymsp[-1].minor.yy107 = yylhsminor.yy107;
        break;
      case 70: /* vector_query ::= vector_command vector_attribute_list */
{
  yymsp[-1].minor.yy107->vn.vq->params = yymsp[0].minor.yy26;
  yylhsminor.yy107 = yymsp[-1].minor.yy107;
}
  yymsp[-1].minor.yy107 = yylhsminor.yy107;
        break;
      case 72: /* vector_score_field ::= as param_term */
{  yy_destructor(yypParser,58,&yymsp[-1].minor);
{
  yymsp[-1].minor.yy0 = yymsp[0].minor.yy0;
}
}
        break;
      case 73: /* vector_score_field ::= as STOPWORD */
{  yy_destructor(yypParser,58,&yymsp[-1].minor);
{
  yymsp[-1].minor.yy0 = yymsp[0].minor.yy0;
  yymsp[-1].minor.yy0.type = QT_TERM;
}
}
        break;
      case 74: /* vector_command ::= TERM param_size modifier ATTRIBUTE */
{
  if (!strncasecmp("KNN", yymsp[-3].minor.yy0.s, yymsp[-3].minor.yy0.len)) {
    yymsp[0].minor.yy0.type = QT_PARAM_VEC;
    yylhsminor.yy107 = NewVectorNode_WithParams(ctx, VECSIM_QT_KNN, &yymsp[-2].minor.yy0, &yymsp[0].minor.yy0);
    yylhsminor.yy107->vn.vq->property = rm_strndup(yymsp[-1].minor.yy0.s, yymsp[-1].minor.yy0.len);
    RedisModule_Assert(-1 != (rm_asprintf(&yylhsminor.yy107->vn.vq->scoreField, "__%.*s_score", yymsp[-1].minor.yy0.len, yymsp[-1].minor.yy0.s)));
  } else {
    reportSyntaxError(ctx->status, &yymsp[-3].minor.yy0, "Syntax error: Expecting Vector Similarity command");
    yylhsminor.yy107 = NULL;
  }
}
  yymsp[-3].minor.yy107 = yylhsminor.yy107;
        break;
      case 75: /* vector_attribute ::= TERM param_term */
{
  const char *value = rm_strndup(yymsp[0].minor.yy0.s, yymsp[0].minor.yy0.len);
  const char *name = rm_strndup(yymsp[-1].minor.yy0.s, yymsp[-1].minor.yy0.len);
  yylhsminor.yy5.param = (VecSimRawParam){ .name = name, .nameLen = yymsp[-1].minor.yy0.len, .value = value, .valLen = yymsp[0].minor.yy0.len };
  if (yymsp[0].minor.yy0.type == QT_PARAM_TERM) {
    yylhsminor.yy5.needResolve = true;
  }
  else { // if yymsp[0].minor.yy0.type == QT_TERM
    yylhsminor.yy5.needResolve = false;
  }
}
  yymsp[-1].minor.yy5 = yylhsminor.yy5;
        break;
      case 76: /* vector_attribute_list ::= vector_attribute_list vector_attribute */
{
  yylhsminor.yy26.params = array_append(yymsp[-1].minor.yy26.params, yymsp[0].minor.yy5.param);
  yylhsminor.yy26.needResolve = array_append(yymsp[-1].minor.yy26.needResolve, yymsp[0].minor.yy5.needResolve);
}
  yymsp[-1].minor.yy26 = yylhsminor.yy26;
        break;
      case 77: /* vector_attribute_list ::= vector_attribute */
{
  yylhsminor.yy26.params = array_new(VecSimRawParam, 1);
  yylhsminor.yy26.needResolve = array_new(bool, 1);
  yylhsminor.yy26.params = array_append(yylhsminor.yy26.params, yymsp[0].minor.yy5.param);
  yylhsminor.yy26.needResolve = array_append(yylhsminor.yy26.needResolve, yymsp[0].minor.yy5.needResolve);
}
  yymsp[0].minor.yy26 = yylhsminor.yy26;
        break;
      case 78: /* num ::= SIZE */
      case 79: /* num ::= NUMBER */ yytestcase(yyruleno==79);
{
  yylhsminor.yy119.num = yymsp[0].minor.yy0.numval;
  yylhsminor.yy119.inclusive = 1;
}
  yymsp[0].minor.yy119 = yylhsminor.yy119;
        break;
      case 80: /* num ::= LP num */
{
  yymsp[-1].minor.yy119=yymsp[0].minor.yy119;
  yymsp[-1].minor.yy119.inclusive = 0;
}
        break;
      case 81: /* num ::= MINUS num */
{
  yymsp[0].minor.yy119.num = -yymsp[0].minor.yy119.num;
  yymsp[-1].minor.yy119 = yymsp[0].minor.yy119;
}
        break;
      case 82: /* term ::= TERM */
      case 83: /* term ::= NUMBER */ yytestcase(yyruleno==83);
      case 84: /* term ::= SIZE */ yytestcase(yyruleno==84);
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 85: /* param_term ::= TERM */
      case 86: /* param_term ::= NUMBER */ yytestcase(yyruleno==86);
      case 87: /* param_term ::= SIZE */ yytestcase(yyruleno==87);
      case 93: /* param_any ::= TERM */ yytestcase(yyruleno==93);
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_TERM;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 88: /* param_term ::= ATTRIBUTE */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_PARAM_TERM;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 89: /* param_size ::= SIZE */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_SIZE;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 90: /* param_size ::= ATTRIBUTE */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_PARAM_SIZE;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 91: /* param_any ::= ATTRIBUTE */
{
  yylhsminor.yy0 = yymsp[0].minor.yy0;
  yylhsminor.yy0.type = QT_PARAM_ANY;
  yylhsminor.yy0.inclusive = 1;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 92: /* param_any ::= LP ATTRIBUTE */
{
  yymsp[-1].minor.yy0 = yymsp[0].minor.yy0;
  yymsp[-1].minor.yy0.type = QT_PARAM_ANY;
  yymsp[-1].minor.yy0.inclusive = 0; // Could be relevant if type is refined
}
        break;
      case 94: /* param_any ::= num */
{
  yylhsminor.yy0.numval = yymsp[0].minor.yy119.num;
  yylhsminor.yy0.inclusive = yymsp[0].minor.yy119.inclusive;
  yylhsminor.yy0.type = QT_NUMERIC;
}
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 96: /* star ::= LP star RP */
{
}
  yy_destructor(yypParser,52,&yymsp[-1].minor);
        break;
      default:
      /* (95) star ::= STAR */ yytestcase(yyruleno==95);
      /* (97) as ::= AS_T */ yytestcase(yyruleno==97);
      /* (98) as ::= AS_S */ yytestcase(yyruleno==98);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  RSQueryParser_v2_ARG_FETCH
  RSQueryParser_v2_CTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  RSQueryParser_v2_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  RSQueryParser_v2_CTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  RSQueryParser_v2_TOKENTYPE yyminor         /* The minor type of the error token */
){
  RSQueryParser_v2_ARG_FETCH
  RSQueryParser_v2_CTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/

  QueryError_SetErrorFmt(ctx->status, QUERY_ESYNTAX,
    "Syntax error at offset %d near %.*s",
    TOKEN.pos, TOKEN.len, TOKEN.s);
/************ End %syntax_error code ******************************************/
  RSQueryParser_v2_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  RSQueryParser_v2_CTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  RSQueryParser_v2_ARG_FETCH
  RSQueryParser_v2_CTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  RSQueryParser_v2_ARG_STORE /* Suppress warning about unused %extra_argument variable */
  RSQueryParser_v2_CTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "RSQueryParser_v2_Alloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void RSQueryParser_v2_(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  RSQueryParser_v2_TOKENTYPE yyminor       /* The value for the token */
  RSQueryParser_v2_ARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  RSQueryParser_v2_CTX_FETCH
  RSQueryParser_v2_ARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor RSQueryParser_v2_CTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int RSQueryParser_v2_Fallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
